import os
from pathlib import Path


STARTER_DATA_DIR = os.path.join(
    os.path.abspath(os.path.dirname(Path(__file__))), "../../data", "2022procthor",
)

STARTER_DATA_DIR_2 = os.path.join(
    os.path.abspath(os.path.dirname(Path(__file__))), "../../data", "2022procthor_new",
)

PROCTHOR_COMMIT_ID = "90eac925dc750818890069e3131f899998dc58b4"
#PROCTHOR_COMMIT_ID = "a9ccb07faf771377c9ff1615bfe7e0ad01968663"

OBJECT_TYPES_WITH_PROPERTIES = {
  "AlarmClock": {"openable": False, "receptacle": False, "pickupable": True},
  "AluminumFoil": {"openable": False, "receptacle": False, "pickupable": True},
  "Apple": {"openable": False, "receptacle": False, "pickupable": True},
  "ArmChair": {"openable": False, "receptacle": True, "pickupable": False},
  "BaseballBat": {"openable": False, "receptacle": False, "pickupable": True},
  "BasketBall": {"openable": False, "receptacle": False, "pickupable": True},
  "Bed": {"openable": False, "receptacle": True, "pickupable": False},
  "Blinds": {"openable": True, "receptacle": False, "pickupable": False},
  "Book": {"openable": True, "receptacle": False, "pickupable": True},
  "Boots": {"openable": False, "receptacle": False, "pickupable": True},
  "Bottle": {"openable": False, "receptacle": False, "pickupable": True},
  "Bowl": {"openable": False, "receptacle": True, "pickupable": True},
  "Box": {"openable": True, "receptacle": True, "pickupable": True},
  "Bread": {"openable": False, "receptacle": False, "pickupable": True},
  "ButterKnife": {"openable": False, "receptacle": False, "pickupable": True},
  "CD": {"openable": False, "receptacle": False, "pickupable": True},
  "Candle": {"openable": False, "receptacle": False, "pickupable": True},
  "Cart": {"openable": False, "receptacle": True, "pickupable": False},
  "CellPhone": {"openable": False, "receptacle": False, "pickupable": True},
  "Chair": {"openable": False, "receptacle": True, "pickupable": False},
  "Cloth": {"openable": False, "receptacle": False, "pickupable": True},
  "ClothesDryer": {"openable": True, "receptacle": True, "pickupable": False},
  "CoffeeMachine": {"openable": False, "receptacle": True, "pickupable": False},
  "CoffeeTable": {"openable": False, "receptacle": True, "pickupable": False},
  "CounterTop": {"openable": False, "receptacle": True, "pickupable": False},
  "CreditCard": {"openable": False, "receptacle": False, "pickupable": True},
  "Cup": {"openable": False, "receptacle": True, "pickupable": True},
  "Desk": {"openable": False, "receptacle": True, "pickupable": False},
  "DeskLamp": {"openable": False, "receptacle": False, "pickupable": False},
  "Desktop": {"openable": False, "receptacle": False, "pickupable": False},
  "DiningTable": {"openable": False, "receptacle": True, "pickupable": False},
  "DishSponge": {"openable": False, "receptacle": False, "pickupable": True},
  "DogBed": {"openable": False, "receptacle": True, "pickupable": False},
  "Doorframe": {"openable": False, "receptacle": False, "pickupable": False},
  "Doorway": {"openable": True, "receptacle": False, "pickupable": False},
  "Dresser": {"openable": False, "receptacle": True, "pickupable": False},
  "Dumbbell": {"openable": False, "receptacle": False, "pickupable": True},
  "Egg": {"openable": False, "receptacle": False, "pickupable": True},
  "Faucet": {"openable": False, "receptacle": False, "pickupable": False},
  "FloorLamp": {"openable": False, "receptacle": False, "pickupable": False},
  "Footstool": {"openable": False, "receptacle": True, "pickupable": True},
  "Fork": {"openable": False, "receptacle": False, "pickupable": True},
  "Fridge": {"openable": True, "receptacle": True, "pickupable": False},
  "GarbageBag": {"openable": False, "receptacle": False, "pickupable": False},
  "GarbageCan": {"openable": False, "receptacle": True, "pickupable": False},
  "HandTowel": {"openable": False, "receptacle": False, "pickupable": True},
  "HandTowelHolder": {"openable": False, "receptacle": True, "pickupable": False},
  "HousePlant": {"openable": False, "receptacle": False, "pickupable": False},
  "Kettle": {"openable": True, "receptacle": False, "pickupable": True},
  "KeyChain": {"openable": False, "receptacle": False, "pickupable": True},
  "Knife": {"openable": False, "receptacle": False, "pickupable": True},
  "Ladle": {"openable": False, "receptacle": False, "pickupable": True},
  "Laptop": {"openable": True, "receptacle": False, "pickupable": True},
  "LaundryHamper": {"openable": True, "receptacle": True, "pickupable": False},
  "Lettuce": {"openable": False, "receptacle": False, "pickupable": True},
  "LightSwitch": {"openable": False, "receptacle": False, "pickupable": False},
  "Microwave": {"openable": True, "receptacle": True, "pickupable": False},
  "Mug": {"openable": False, "receptacle": True, "pickupable": True},
  "Newspaper": {"openable": False, "receptacle": False, "pickupable": True},
  "Ottoman": {"openable": False, "receptacle": True, "pickupable": False},
  "Painting": {"openable": False, "receptacle": False, "pickupable": False},
  "Pan": {"openable": False, "receptacle": True, "pickupable": True},
  "PaperTowelRoll": {"openable": False, "receptacle": False, "pickupable": True},
  "Pen": {"openable": False, "receptacle": False, "pickupable": True},
  "Pencil": {"openable": False, "receptacle": False, "pickupable": True},
  "PepperShaker": {"openable": False, "receptacle": False, "pickupable": True},
  "Pillow": {"openable": False, "receptacle": False, "pickupable": True},
  "Plate": {"openable": False, "receptacle": True, "pickupable": True},
  "Plunger": {"openable": False, "receptacle": False, "pickupable": True},
  "Pot": {"openable": False, "receptacle": True, "pickupable": True},
  "Potato": {"openable": False, "receptacle": False, "pickupable": True},
  "RemoteControl": {"openable": False, "receptacle": False, "pickupable": True},
  "RoomDecor": {"openable": False, "receptacle": False, "pickupable": False},
  "Safe": {"openable": True, "receptacle": True, "pickupable": False},
  "SaltShaker": {"openable": False, "receptacle": False, "pickupable": True},
  "ScrubBrush": {"openable": False, "receptacle": False, "pickupable": True},
  "ShelvingUnit": {"openable": False, "receptacle": True, "pickupable": False},
  "ShowerCurtain": {"openable": True, "receptacle": False, "pickupable": False},
  "ShowerHead": {"openable": False, "receptacle": False, "pickupable": False},
  "SideTable": {"openable": False, "receptacle": True, "pickupable": False},
  "Sink": {"openable": False, "receptacle": True, "pickupable": False},
  "SoapBar": {"openable": False, "receptacle": False, "pickupable": True},
  "SoapBottle": {"openable": False, "receptacle": False, "pickupable": True},
  "Sofa": {"openable": False, "receptacle": True, "pickupable": False},
  "Spatula": {"openable": False, "receptacle": False, "pickupable": True},
  "Spoon": {"openable": False, "receptacle": False, "pickupable": True},
  "SprayBottle": {"openable": False, "receptacle": False, "pickupable": True},
  "Statue": {"openable": False, "receptacle": False, "pickupable": True},
  "Stool": {"openable": False, "receptacle": True, "pickupable": False},
  "TVStand": {"openable": False, "receptacle": True, "pickupable": False},
  "TableTopDecor": {"openable": False, "receptacle": False, "pickupable": True},
  "TeddyBear": {"openable": False, "receptacle": False, "pickupable": True},
  "Television": {"openable": False, "receptacle": False, "pickupable": False},
  "TennisRacket": {"openable": False, "receptacle": False, "pickupable": True},
  "TissueBox": {"openable": False, "receptacle": False, "pickupable": True},
  "Toaster": {"openable": False, "receptacle": True, "pickupable": False},
  "Toilet": {"openable": True, "receptacle": True, "pickupable": False},
  "ToiletPaper": {"openable": False, "receptacle": False, "pickupable": True},
  "ToiletPaperHanger": {"openable": False, "receptacle": True, "pickupable": False},
  "Tomato": {"openable": False, "receptacle": False, "pickupable": True},
  "Towel": {"openable": False, "receptacle": False, "pickupable": True},
  "TowelHolder": {"openable": False, "receptacle": True, "pickupable": False},
  "VacuumCleaner": {"openable": False, "receptacle": False, "pickupable": False},
  "Vase": {"openable": False, "receptacle": False, "pickupable": True},
  "WashingMachine": {"openable": True, "receptacle": True, "pickupable": False},
  "Watch": {"openable": False, "receptacle": False, "pickupable": True},
  "WateringCan": {"openable": False, "receptacle": False, "pickupable": True},
  "Window": {"openable": False, "receptacle": False, "pickupable": False},
  "WineBottle": {"openable": False, "receptacle": False, "pickupable": True}
}

ASSET_TO_OBJECT = {
  "Alarm_Clock_1": "AlarmClock",
  "Alarm_Clock_10": "AlarmClock",
  "Alarm_Clock_11": "AlarmClock",
  "Alarm_Clock_12": "AlarmClock",
  "Alarm_Clock_13": "AlarmClock",
  "Alarm_Clock_14": "AlarmClock",
  "Alarm_Clock_15": "AlarmClock",
  "Alarm_Clock_16": "AlarmClock",
  "Alarm_Clock_17": "AlarmClock",
  "Alarm_Clock_18": "AlarmClock",
  "Alarm_Clock_19": "AlarmClock",
  "Alarm_Clock_2": "AlarmClock",
  "Alarm_Clock_20": "AlarmClock",
  "Alarm_Clock_21": "AlarmClock",
  "Alarm_Clock_22": "AlarmClock",
  "Alarm_Clock_23": "AlarmClock",
  "Alarm_Clock_24": "AlarmClock",
  "Alarm_Clock_25": "AlarmClock",
  "Alarm_Clock_26": "AlarmClock",
  "Alarm_Clock_27": "AlarmClock",
  "Alarm_Clock_28": "AlarmClock",
  "Alarm_Clock_29": "AlarmClock",
  "Alarm_Clock_3": "AlarmClock",
  "Alarm_Clock_30": "AlarmClock",
  "Alarm_Clock_4": "AlarmClock",
  "Alarm_Clock_5": "AlarmClock",
  "Alarm_Clock_6": "AlarmClock",
  "Alarm_Clock_7": "AlarmClock",
  "Alarm_Clock_8": "AlarmClock",
  "Alarm_Clock_9": "AlarmClock",
  "RoboTHOR_alarm_clock_bajk_v": "AlarmClock",
  "Aluminum_Foil_1": "AluminumFoil",
  "Apple_1": "Apple",
  "Apple_10": "Apple",
  "Apple_11": "Apple",
  "Apple_12": "Apple",
  "Apple_13": "Apple",
  "Apple_14": "Apple",
  "Apple_15": "Apple",
  "Apple_16": "Apple",
  "Apple_17": "Apple",
  "Apple_18": "Apple",
  "Apple_19": "Apple",
  "Apple_2": "Apple",
  "Apple_20": "Apple",
  "Apple_21": "Apple",
  "Apple_22": "Apple",
  "Apple_23": "Apple",
  "Apple_24": "Apple",
  "Apple_25": "Apple",
  "Apple_26": "Apple",
  "Apple_27": "Apple",
  "Apple_28": "Apple",
  "Apple_29": "Apple",
  "Apple_3": "Apple",
  "Apple_30": "Apple",
  "Apple_4": "Apple",
  "Apple_5": "Apple",
  "Apple_6": "Apple",
  "Apple_7": "Apple",
  "Apple_8": "Apple",
  "Apple_9": "Apple",
  "RoboTHOR_apple_ai2_1_v": "Apple",
  "ArmChair_213_1": "ArmChair",
  "ArmChair_216_1": "ArmChair",
  "Armchair_201_1": "ArmChair",
  "Armchair_201_2": "ArmChair",
  "Armchair_201_3": "ArmChair",
  "Armchair_201_4": "ArmChair",
  "Armchair_201_5": "ArmChair",
  "Armchair_202_1": "ArmChair",
  "Armchair_203_1": "ArmChair",
  "Armchair_204_1": "ArmChair",
  "Armchair_205_1_1": "ArmChair",
  "Armchair_205_1_2": "ArmChair",
  "Armchair_205_2_1": "ArmChair",
  "Armchair_207_1": "ArmChair",
  "Armchair_207_2": "ArmChair",
  "Armchair_207_3": "ArmChair",
  "Armchair_207_4": "ArmChair",
  "Armchair_208_1": "ArmChair",
  "Armchair_208_2": "ArmChair",
  "Armchair_208_3": "ArmChair",
  "Armchair_208_4": "ArmChair",
  "Armchair_208_5": "ArmChair",
  "Armchair_210_1": "ArmChair",
  "Armchair_217_1": "ArmChair",
  "Armchair_219_1": "ArmChair",
  "Armchair_219_2": "ArmChair",
  "Armchair_220_1": "ArmChair",
  "Armchair_222_1": "ArmChair",
  "Armchair_225_1": "ArmChair",
  "Armchair_226_1": "ArmChair",
  "Armchair_227_1": "ArmChair",
  "Armchair_230_1": "ArmChair",
  "RoboTHOR_armchair_ekenas_v": "ArmChair",
  "RoboTHOR_armchair_ektorp": "ArmChair",
  "RoboTHOR_armchair_emmabo": "ArmChair",
  "RoboTHOR_armchair_karlstad": "ArmChair",
  "RoboTHOR_armchair_overallt": "ArmChair",
  "RoboTHOR_armchair_tullsta": "ArmChair",
  "BaseballBat_1": "BaseballBat",
  "BaseballBat_2": "BaseballBat",
  "BaseballBat_3": "BaseballBat",
  "BaseballBat_4": "BaseballBat",
  "RoboTHOR_baseball_bat_rawlings_v": "BaseballBat",
  "Basketball_1": "BasketBall",
  "RoboTHOR_basketball_rhode_island_novelty_v": "BasketBall",
  "Bed_1": "Bed",
  "Bed_10": "Bed",
  "Bed_11": "Bed",
  "Bed_12": "Bed",
  "Bed_13": "Bed",
  "Bed_14": "Bed",
  "Bed_15": "Bed",
  "Bed_16": "Bed",
  "Bed_17": "Bed",
  "Bed_18_1": "Bed",
  "Bed_18_2": "Bed",
  "Bed_19": "Bed",
  "Bed_2": "Bed",
  "Bed_20": "Bed",
  "Bed_21": "Bed",
  "Bed_22": "Bed",
  "Bed_23": "Bed",
  "Bed_24": "Bed",
  "Bed_25": "Bed",
  "Bed_26_1": "Bed",
  "Bed_26_2": "Bed",
  "Bed_27": "Bed",
  "Bed_28": "Bed",
  "Bed_29": "Bed",
  "Bed_3": "Bed",
  "Bed_30": "Bed",
  "Bed_4": "Bed",
  "Bed_5": "Bed",
  "Bed_6": "Bed",
  "Bed_7": "Bed",
  "Bed_8": "Bed",
  "Bed_9": "Bed",
  "RoboTHOR_bed_grankulla": "Bed",
  "RoboTHOR_bed_hemnes": "Bed",
  "RoboTHOR_bed_kritter": "Bed",
  "RoboTHOR_bed_meldal": "Bed",
  "RoboTHOR_bed_tarva_v": "Bed",
  "RoboTHOR_hemnes_day_bed": "Bed",
  "Blinds_1": "Blinds",
  "Book_1": "Book",
  "Book_10": "Book",
  "Book_11": "Book",
  "Book_12": "Book",
  "Book_13": "Book",
  "Book_14": "Book",
  "Book_15": "Book",
  "Book_16": "Book",
  "Book_17": "Book",
  "Book_18": "Book",
  "Book_19": "Book",
  "Book_2": "Book",
  "Book_20": "Book",
  "Book_21": "Book",
  "Book_22": "Book",
  "Book_23": "Book",
  "Book_24": "Book",
  "Book_25": "Book",
  "Book_26": "Book",
  "Book_27": "Book",
  "Book_28": "Book",
  "Book_29": "Book",
  "Book_3": "Book",
  "Book_30": "Book",
  "Book_4": "Book",
  "Book_5": "Book",
  "Book_6": "Book",
  "Book_7": "Book",
  "Book_8": "Book",
  "Book_9": "Book",
  "RoboTHOR_book_ai2_1_v": "Book",
  "RoboTHOR_book_ai2_2_v": "Book",
  "RoboTHOR_book_ai2_3_v": "Book",
  "RoboTHOR_book_ai2_5_v": "Book",
  "RoboTHOR_book_ai2_6_v": "Book",
  "Boot_1": "Boots",
  "Bottle_1": "Bottle",
  "Bowl_1": "Bowl",
  "Bowl_10": "Bowl",
  "Bowl_11": "Bowl",
  "Bowl_12": "Bowl",
  "Bowl_13": "Bowl",
  "Bowl_14": "Bowl",
  "Bowl_15": "Bowl",
  "Bowl_16": "Bowl",
  "Bowl_17": "Bowl",
  "Bowl_18": "Bowl",
  "Bowl_19": "Bowl",
  "Bowl_2": "Bowl",
  "Bowl_20": "Bowl",
  "Bowl_21": "Bowl",
  "Bowl_22": "Bowl",
  "Bowl_23": "Bowl",
  "Bowl_24": "Bowl",
  "Bowl_25": "Bowl",
  "Bowl_26": "Bowl",
  "Bowl_27": "Bowl",
  "Bowl_28": "Bowl",
  "Bowl_29": "Bowl",
  "Bowl_3": "Bowl",
  "Bowl_30": "Bowl",
  "Bowl_4": "Bowl",
  "Bowl_5": "Bowl",
  "Bowl_6": "Bowl",
  "Bowl_7": "Bowl",
  "Bowl_8": "Bowl",
  "Bowl_9": "Bowl",
  "RoboTHOR_bowl_ai2_v": "Bowl",
  "Box_1": "Box",
  "Box_10": "Box",
  "Box_11": "Box",
  "Box_12": "Box",
  "Box_13": "Box",
  "Box_14": "Box",
  "Box_15": "Box",
  "Box_16": "Box",
  "Box_17": "Box",
  "Box_18": "Box",
  "Box_19": "Box",
  "Box_2": "Box",
  "Box_20": "Box",
  "Box_21": "Box",
  "Box_22": "Box",
  "Box_23": "Box",
  "Box_24": "Box",
  "Box_25": "Box",
  "Box_26": "Box",
  "Box_27": "Box",
  "Box_28": "Box",
  "Box_29": "Box",
  "Box_3": "Box",
  "Box_30": "Box",
  "Box_4": "Box",
  "Box_5": "Box",
  "Box_6": "Box",
  "Box_7": "Box",
  "Box_8": "Box",
  "Box_9": "Box",
  "DecorativeBox1": "Box",
  "DecorativeBox2": "Box",
  "DecorativeBox3": "Box",
  "DecorativeBox4": "Box",
  "Bread_1": "Bread",
  "Bread_10": "Bread",
  "Bread_11": "Bread",
  "Bread_12": "Bread",
  "Bread_13": "Bread",
  "Bread_14": "Bread",
  "Bread_15": "Bread",
  "Bread_16": "Bread",
  "Bread_17": "Bread",
  "Bread_18": "Bread",
  "Bread_19": "Bread",
  "Bread_2": "Bread",
  "Bread_20": "Bread",
  "Bread_21": "Bread",
  "Bread_22": "Bread",
  "Bread_23": "Bread",
  "Bread_24": "Bread",
  "Bread_25": "Bread",
  "Bread_26": "Bread",
  "Bread_27": "Bread",
  "Bread_28": "Bread",
  "Bread_29": "Bread",
  "Bread_3": "Bread",
  "Bread_30": "Bread",
  "Bread_4": "Bread",
  "Bread_5": "Bread",
  "Bread_6": "Bread",
  "Bread_7": "Bread",
  "Bread_8": "Bread",
  "Bread_9": "Bread",
  "ButterKnife_1": "ButterKnife",
  "RoboTHOR_butter_knife_ai2_1_v": "ButterKnife",
  "CD_1": "CD",
  "Candle_1": "Candle",
  "Candle_2": "Candle",
  "Candle_3": "Candle",
  "Candle_4": "Candle",
  "Candle_5": "Candle",
  "Candle_6": "Candle",
  "RoboTHOR_candle_glittrig_1_v": "Candle",
  "RoboTHOR_candle_glittrig_2_v": "Candle",
  "RoboTHOR_candle_glittrig_3_v": "Candle",
  "Cart_1": "Cart",
  "Cellphone_1": "CellPhone",
  "Cellphone_2": "CellPhone",
  "Cellphone_3": "CellPhone",
  "Cellphone_4": "CellPhone",
  "Cellphone_5": "CellPhone",
  "Cellphone_6": "CellPhone",
  "Cellphone_7": "CellPhone",
  "Cellphone_8": "CellPhone",
  "RoboTHOR_cellphone_blackberry_v": "CellPhone",
  "Chair_002_1": "Chair",
  "Chair_002_2": "Chair",
  "Chair_002_3": "Chair",
  "Chair_007_1": "Chair",
  "Chair_007_2": "Chair",
  "Chair_007_3": "Chair",
  "Chair_007_4": "Chair",
  "Chair_007_5": "Chair",
  "Chair_201_1": "Chair",
  "Chair_203_1": "Chair",
  "Chair_203_2": "Chair",
  "Chair_203_3": "Chair",
  "Chair_204_1": "Chair",
  "Chair_204_2": "Chair",
  "Chair_204_3": "Chair",
  "Chair_204_4": "Chair",
  "Chair_204_5": "Chair",
  "Chair_204_6": "Chair",
  "Chair_204_7": "Chair",
  "Chair_204_8": "Chair",
  "Chair_205_1": "Chair",
  "Chair_205_2": "Chair",
  "Chair_205_3": "Chair",
  "Chair_205_4": "Chair",
  "Chair_205_5": "Chair",
  "Chair_210_1": "Chair",
  "Chair_210_2": "Chair",
  "Chair_210_3": "Chair",
  "Chair_215_1": "Chair",
  "Chair_215_2": "Chair",
  "Chair_215_3": "Chair",
  "Chair_223_1": "Chair",
  "Chair_224_1": "Chair",
  "Chair_227_1": "Chair",
  "Chair_230_1": "Chair",
  "Chair_303_1": "Chair",
  "Chair_303_2": "Chair",
  "Chair_304_1": "Chair",
  "Chair_305_1": "Chair",
  "Chair_307_1": "Chair",
  "Chair_307_2": "Chair",
  "Chair_311_1": "Chair",
  "Chair_313_1": "Chair",
  "Chair_318_1": "Chair",
  "RoboTHOR_chair_antnas": "Chair",
  "RoboTHOR_chair_extendable": "Chair",
  "RoboTHOR_chair_jokkmokk_v": "Chair",
  "RoboTHOR_chair_liatorp": "Chair",
  "RoboTHOR_chair_mella": "Chair",
  "RoboTHOR_chair_norden_gateleg": "Chair",
  "RoboTHOR_office_chair_allak": "Chair",
  "RoboTHOR_office_chair_jules": "Chair",
  "RoboTHOR_office_chair_molte_v": "Chair",
  "RoboTHOR_office_chair_sevnning": "Chair",
  "RoboTHOR_office_chair_skruvsta": "Chair",
  "RoboTHOR_office_chair_volmar": "Chair",
  "Cloth_1": "Cloth",
  "Cloth_10": "Cloth",
  "Cloth_11": "Cloth",
  "Cloth_12": "Cloth",
  "Cloth_2": "Cloth",
  "Cloth_3": "Cloth",
  "Cloth_4": "Cloth",
  "Cloth_5": "Cloth",
  "Cloth_6": "Cloth",
  "Cloth_7": "Cloth",
  "Cloth_8": "Cloth",
  "Cloth_9": "Cloth",
  "Clothes_Dryer_1": "ClothesDryer",
  "Clothes_Dryer_2": "ClothesDryer",
  "coffee_machine_1": "CoffeeMachine",
  "coffee_machine_10": "CoffeeMachine",
  "coffee_machine_11": "CoffeeMachine",
  "coffee_machine_12": "CoffeeMachine",
  "coffee_machine_13": "CoffeeMachine",
  "coffee_machine_14": "CoffeeMachine",
  "coffee_machine_15": "CoffeeMachine",
  "coffee_machine_16": "CoffeeMachine",
  "coffee_machine_17": "CoffeeMachine",
  "coffee_machine_18": "CoffeeMachine",
  "coffee_machine_19": "CoffeeMachine",
  "coffee_machine_2": "CoffeeMachine",
  "coffee_machine_20": "CoffeeMachine",
  "coffee_machine_21": "CoffeeMachine",
  "coffee_machine_22": "CoffeeMachine",
  "coffee_machine_23": "CoffeeMachine",
  "coffee_machine_24": "CoffeeMachine",
  "coffee_machine_25": "CoffeeMachine",
  "coffee_machine_26": "CoffeeMachine",
  "coffee_machine_27": "CoffeeMachine",
  "coffee_machine_28": "CoffeeMachine",
  "coffee_machine_29": "CoffeeMachine",
  "coffee_machine_3": "CoffeeMachine",
  "coffee_machine_30": "CoffeeMachine",
  "coffee_machine_4": "CoffeeMachine",
  "coffee_machine_5": "CoffeeMachine",
  "coffee_machine_6": "CoffeeMachine",
  "coffee_machine_7": "CoffeeMachine",
  "coffee_machine_8": "CoffeeMachine",
  "coffee_machine_9": "CoffeeMachine",
  "Coffee_Table_201_1": "CoffeeTable",
  "Coffee_Table_202_1": "CoffeeTable",
  "Coffee_Table_202_2": "CoffeeTable",
  "Coffee_Table_203_1": "CoffeeTable",
  "Coffee_Table_204_1": "CoffeeTable",
  "Coffee_Table_206_1": "CoffeeTable",
  "Coffee_Table_206_2": "CoffeeTable",
  "Coffee_Table_206_3": "CoffeeTable",
  "Coffee_Table_207_1": "CoffeeTable",
  "Coffee_Table_209_1": "CoffeeTable",
  "Coffee_Table_211_1": "CoffeeTable",
  "Coffee_Table_213_1": "CoffeeTable",
  "Coffee_Table_214_1": "CoffeeTable",
  "Coffee_Table_215_1": "CoffeeTable",
  "Coffee_Table_215_2": "CoffeeTable",
  "Coffee_Table_217_1": "CoffeeTable",
  "Coffee_Table_218_1": "CoffeeTable",
  "Coffee_Table_221_1": "CoffeeTable",
  "Coffee_Table_222_1": "CoffeeTable",
  "Coffee_Table_225_1": "CoffeeTable",
  "Coffee_Table_227_1_1": "CoffeeTable",
  "Coffee_Table_227_2_1": "CoffeeTable",
  "Coffee_Table_228_1": "CoffeeTable",
  "Coffee_Table_229_1": "CoffeeTable",
  "Coffee_Table_230_1": "CoffeeTable",
  "Coffee_Table_315_1": "CoffeeTable",
  "RoboTHOR_coffee_table_bankas": "CoffeeTable",
  "RoboTHOR_coffee_table_fjallbo_v": "CoffeeTable",
  "RoboTHOR_coffee_table_hemnes": "CoffeeTable",
  "RoboTHOR_coffee_table_kragsta": "CoffeeTable",
  "RoboTHOR_coffee_table_lisabo": "CoffeeTable",
  "RoboTHOR_coffee_table_vejmon": "CoffeeTable",
  "Countertop_C_10x10": "CounterTop",
  "Countertop_C_10x4": "CounterTop",
  "Countertop_C_10x6": "CounterTop",
  "Countertop_C_10x8": "CounterTop",
  "Countertop_C_8x10": "CounterTop",
  "Countertop_C_8x4": "CounterTop",
  "Countertop_C_8x6": "CounterTop",
  "Countertop_C_8x8": "CounterTop",
  "Countertop_I_10x2": "CounterTop",
  "Countertop_I_2x2": "CounterTop",
  "Countertop_I_4x2": "CounterTop",
  "Countertop_I_6x2": "CounterTop",
  "Countertop_I_8x2": "CounterTop",
  "Countertop_Island_10x3": "CounterTop",
  "Countertop_Island_4x3": "CounterTop",
  "Countertop_Island_6x3": "CounterTop",
  "Countertop_Island_8x3": "CounterTop",
  "Countertop_L_10x10": "CounterTop",
  "Countertop_L_10x4": "CounterTop",
  "Countertop_L_10x6": "CounterTop",
  "Countertop_L_10x8": "CounterTop",
  "Countertop_L_4x10": "CounterTop",
  "Countertop_L_4x4": "CounterTop",
  "Countertop_L_4x6": "CounterTop",
  "Countertop_L_4x8": "CounterTop",
  "Countertop_L_6x10": "CounterTop",
  "Countertop_L_6x4": "CounterTop",
  "Countertop_L_6x6": "CounterTop",
  "Countertop_L_6x8": "CounterTop",
  "Countertop_L_8x10": "CounterTop",
  "Countertop_L_8x4": "CounterTop",
  "Countertop_L_8x6": "CounterTop",
  "Countertop_L_8x8": "CounterTop",
  "CreditCard_1": "CreditCard",
  "CreditCard_2": "CreditCard",
  "CreditCard_3": "CreditCard",
  "CreditCard_4": "CreditCard",
  "Cup_1": "Cup",
  "Cup_10": "Cup",
  "Cup_11": "Cup",
  "Cup_12": "Cup",
  "Cup_13": "Cup",
  "Cup_14": "Cup",
  "Cup_15": "Cup",
  "Cup_16": "Cup",
  "Cup_17": "Cup",
  "Cup_18": "Cup",
  "Cup_19": "Cup",
  "Cup_2": "Cup",
  "Cup_20": "Cup",
  "Cup_21": "Cup",
  "Cup_22": "Cup",
  "Cup_23": "Cup",
  "Cup_24": "Cup",
  "Cup_25": "Cup",
  "Cup_26": "Cup",
  "Cup_27": "Cup",
  "Cup_28": "Cup",
  "Cup_29": "Cup",
  "Cup_3": "Cup",
  "Cup_30": "Cup",
  "Cup_4": "Cup",
  "Cup_5": "Cup",
  "Cup_6": "Cup",
  "Cup_7": "Cup",
  "Cup_8": "Cup",
  "Cup_9": "Cup",
  "RoboTHOR_cup_ai2_v": "Cup",
  "Desk_204_1": "Desk",
  "Desk_229_1": "Desk",
  "Desk_301_1": "Desk",
  "Desk_302_1": "Desk",
  "Desk_303_1": "Desk",
  "Desk_304_1": "Desk",
  "Desk_305_1": "Desk",
  "Desk_306_1": "Desk",
  "Desk_307_1_1": "Desk",
  "Desk_307_2_1": "Desk",
  "Desk_308_1_1": "Desk",
  "Desk_308_2_1": "Desk",
  "Desk_310_1": "Desk",
  "Desk_311_1": "Desk",
  "Desk_312_1": "Desk",
  "Desk_313_1": "Desk",
  "Desk_313_2": "Desk",
  "Desk_314_1": "Desk",
  "Desk_315_1": "Desk",
  "Desk_316_1": "Desk",
  "Desk_318_1": "Desk",
  "Desk_320_1_1": "Desk",
  "Desk_320_2_1": "Desk",
  "Desk_321_1": "Desk",
  "Desk_323_1": "Desk",
  "Desk_326_1": "Desk",
  "Desk_327_1": "Desk",
  "Desk_328_1": "Desk",
  "Desk_329_1": "Desk",
  "RoboTHOR_desk_alve": "Desk",
  "RoboTHOR_desk_fjallbo_v": "Desk",
  "RoboTHOR_desk_gustav": "Desk",
  "RoboTHOR_desk_lillasen": "Desk",
  "RoboTHOR_desk_lisabo": "Desk",
  "RoboTHOR_desk_norrasen": "Desk",
  "Desk_Lamp_1": "DeskLamp",
  "Desk_Lamp_10": "DeskLamp",
  "Desk_Lamp_11": "DeskLamp",
  "Desk_Lamp_12": "DeskLamp",
  "Desk_Lamp_13": "DeskLamp",
  "Desk_Lamp_2": "DeskLamp",
  "Desk_Lamp_3": "DeskLamp",
  "Desk_Lamp_4": "DeskLamp",
  "Desk_Lamp_5": "DeskLamp",
  "Desk_Lamp_6": "DeskLamp",
  "Desk_Lamp_7": "DeskLamp",
  "Desk_Lamp_8": "DeskLamp",
  "Desk_Lamp_9": "DeskLamp",
  "RoboTHOR_desk_lamp_ai2_v": "DeskLamp",
  "RoboTHOR_desk_lamp_arstid_v": "DeskLamp",
  "Desktop_316_1": "Desktop",
  "Dining_Table_16_1": "DiningTable",
  "Dining_Table_16_2": "DiningTable",
  "Dining_Table_201_1": "DiningTable",
  "Dining_Table_203_1": "DiningTable",
  "Dining_Table_204_1": "DiningTable",
  "Dining_Table_205_1": "DiningTable",
  "Dining_Table_208_1": "DiningTable",
  "Dining_Table_208_2": "DiningTable",
  "Dining_Table_216_1": "DiningTable",
  "Dining_Table_218_1": "DiningTable",
  "Dining_Table_21_1": "DiningTable",
  "Dining_Table_21_2": "DiningTable",
  "Dining_Table_21_3": "DiningTable",
  "Dining_Table_221_1": "DiningTable",
  "Dining_Table_223_1": "DiningTable",
  "Dining_Table_227_1": "DiningTable",
  "Dining_Table_228_1": "DiningTable",
  "Dining_Table_230_1": "DiningTable",
  "Dining_Table_23_1": "DiningTable",
  "Dining_Table_23_2": "DiningTable",
  "Dining_Table_23_3": "DiningTable",
  "Dining_Table_27_1": "DiningTable",
  "Dining_Table_7_1": "DiningTable",
  "Dining_Table_9_1": "DiningTable",
  "RoboTHOR_dining_table_antas": "DiningTable",
  "RoboTHOR_dining_table_extendable": "DiningTable",
  "RoboTHOR_dining_table_jokkmokk_v": "DiningTable",
  "RoboTHOR_dining_table_liatorp": "DiningTable",
  "RoboTHOR_dining_table_mella": "DiningTable",
  "RoboTHOR_dining_table_norden_gateleg": "DiningTable",
  "Dish_Sponge_1": "DishSponge",
  "Dog_Bed_1_1": "DogBed",
  "Dog_Bed_1_2": "DogBed",
  "Dog_Bed_2_1": "DogBed",
  "Doorframe_1": "Doorframe",
  "Doorframe_10": "Doorframe",
  "Doorframe_2": "Doorframe",
  "Doorframe_3": "Doorframe",
  "Doorframe_4": "Doorframe",
  "Doorframe_5": "Doorframe",
  "Doorframe_6": "Doorframe",
  "Doorframe_7": "Doorframe",
  "Doorframe_8": "Doorframe",
  "Doorframe_9": "Doorframe",
  "Doorframe_Double_1": "Doorframe",
  "Doorframe_Double_10": "Doorframe",
  "Doorframe_Double_2": "Doorframe",
  "Doorframe_Double_3": "Doorframe",
  "Doorframe_Double_4": "Doorframe",
  "Doorframe_Double_5": "Doorframe",
  "Doorframe_Double_6": "Doorframe",
  "Doorframe_Double_7": "Doorframe",
  "Doorframe_Double_8": "Doorframe",
  "Doorframe_Double_9": "Doorframe",
  "Doorway_1": "Doorway",
  "Doorway_10": "Doorway",
  "Doorway_2": "Doorway",
  "Doorway_3": "Doorway",
  "Doorway_4": "Doorway",
  "Doorway_5": "Doorway",
  "Doorway_6": "Doorway",
  "Doorway_7": "Doorway",
  "Doorway_8": "Doorway",
  "Doorway_9": "Doorway",
  "Doorway_Double_1": "Doorway",
  "Doorway_Double_10": "Doorway",
  "Doorway_Double_2": "Doorway",
  "Doorway_Double_3": "Doorway",
  "Doorway_Double_4": "Doorway",
  "Doorway_Double_5": "Doorway",
  "Doorway_Double_6": "Doorway",
  "Doorway_Double_7": "Doorway",
  "Doorway_Double_8": "Doorway",
  "Doorway_Double_9": "Doorway",
  "Dresser_205_1": "Dresser",
  "Dresser_209_1": "Dresser",
  "Dresser_210_1_1": "Dresser",
  "Dresser_210_2_1": "Dresser",
  "Dresser_213_1": "Dresser",
  "Dresser_217_1": "Dresser",
  "Dresser_218_1": "Dresser",
  "Dresser_219_1": "Dresser",
  "Dresser_220_1": "Dresser",
  "Dresser_224_1": "Dresser",
  "Dresser_229_1": "Dresser",
  "Dresser_301_1": "Dresser",
  "Dresser_315_1": "Dresser",
  "Dresser_315_2": "Dresser",
  "Dresser_315_3": "Dresser",
  "Dresser_318_1": "Dresser",
  "Dresser_318_2": "Dresser",
  "Dresser_319_1": "Dresser",
  "Dresser_319_2": "Dresser",
  "Dresser_323_1": "Dresser",
  "Dresser_325_1": "Dresser",
  "Dresser_413_1": "Dresser",
  "RoboTHOR_dresser_aneboda": "Dresser",
  "RoboTHOR_dresser_anes": "Dresser",
  "RoboTHOR_dresser_aspelund": "Dresser",
  "RoboTHOR_dresser_birkeland": "Dresser",
  "RoboTHOR_dresser_hemnes": "Dresser",
  "RoboTHOR_dresser_rast_v": "Dresser",
  "Dumbbell_1_1": "Dumbbell",
  "Egg_1": "Egg",
  "Egg_10": "Egg",
  "Egg_11": "Egg",
  "Egg_12": "Egg",
  "Egg_13": "Egg",
  "Egg_14": "Egg",
  "Egg_15": "Egg",
  "Egg_16": "Egg",
  "Egg_17": "Egg",
  "Egg_18": "Egg",
  "Egg_19": "Egg",
  "Egg_2": "Egg",
  "Egg_20": "Egg",
  "Egg_21": "Egg",
  "Egg_22": "Egg",
  "Egg_23": "Egg",
  "Egg_24": "Egg",
  "Egg_25": "Egg",
  "Egg_26": "Egg",
  "Egg_27": "Egg",
  "Egg_28": "Egg",
  "Egg_29": "Egg",
  "Egg_3": "Egg",
  "Egg_30": "Egg",
  "Egg_4": "Egg",
  "Egg_5": "Egg",
  "Egg_6": "Egg",
  "Egg_7": "Egg",
  "Egg_8": "Egg",
  "Egg_9": "Egg",
  "Bathroom_Faucet_1": "Faucet",
  "Bathroom_Faucet_10": "Faucet",
  "Bathroom_Faucet_11": "Faucet",
  "Bathroom_Faucet_12": "Faucet",
  "Bathroom_Faucet_13": "Faucet",
  "Bathroom_Faucet_14": "Faucet",
  "Bathroom_Faucet_15": "Faucet",
  "Bathroom_Faucet_17": "Faucet",
  "Bathroom_Faucet_18": "Faucet",
  "Bathroom_Faucet_19": "Faucet",
  "Bathroom_Faucet_2": "Faucet",
  "Bathroom_Faucet_20": "Faucet",
  "Bathroom_Faucet_21": "Faucet",
  "Bathroom_Faucet_22": "Faucet",
  "Bathroom_Faucet_25": "Faucet",
  "Bathroom_Faucet_26": "Faucet",
  "Bathroom_Faucet_27": "Faucet",
  "Bathroom_Faucet_28": "Faucet",
  "Bathroom_Faucet_3": "Faucet",
  "Bathroom_Faucet_30": "Faucet",
  "Bathroom_Faucet_5": "Faucet",
  "Bathroom_Faucet_7": "Faucet",
  "Bathroom_Faucet_8": "Faucet",
  "Bathroom_Faucet_9": "Faucet",
  "Bathtub_Faucet_1": "Faucet",
  "Bathtub_Faucet_2": "Faucet",
  "Bathtub_Faucet_3": "Faucet",
  "Bathtub_Faucet_4": "Faucet",
  "Bathtub_Faucet_5": "Faucet",
  "Bathtub_Faucet_6": "Faucet",
  "Bathtub_Faucet_7": "Faucet",
  "Bathtub_Faucet_8": "Faucet",
  "Kitchen_Faucet_1": "Faucet",
  "Kitchen_Faucet_2": "Faucet",
  "Kitchen_Faucet_3": "Faucet",
  "Kitchen_Faucet_4": "Faucet",
  "Kitchen_Faucet_5": "Faucet",
  "Floor_Lamp_1": "FloorLamp",
  "Floor_Lamp_10": "FloorLamp",
  "Floor_Lamp_11": "FloorLamp",
  "Floor_Lamp_12": "FloorLamp",
  "Floor_Lamp_13": "FloorLamp",
  "Floor_Lamp_14": "FloorLamp",
  "Floor_Lamp_15": "FloorLamp",
  "Floor_Lamp_16": "FloorLamp",
  "Floor_Lamp_17": "FloorLamp",
  "Floor_Lamp_18": "FloorLamp",
  "Floor_Lamp_19": "FloorLamp",
  "Floor_Lamp_2": "FloorLamp",
  "Floor_Lamp_20": "FloorLamp",
  "Floor_Lamp_21": "FloorLamp",
  "Floor_Lamp_22": "FloorLamp",
  "Floor_Lamp_23": "FloorLamp",
  "Floor_Lamp_24": "FloorLamp",
  "Floor_Lamp_25": "FloorLamp",
  "Floor_Lamp_26": "FloorLamp",
  "Floor_Lamp_27": "FloorLamp",
  "Floor_Lamp_28": "FloorLamp",
  "Floor_Lamp_29": "FloorLamp",
  "Floor_Lamp_3": "FloorLamp",
  "Floor_Lamp_30": "FloorLamp",
  "Floor_Lamp_4": "FloorLamp",
  "Floor_Lamp_5": "FloorLamp",
  "Floor_Lamp_6": "FloorLamp",
  "Floor_Lamp_7": "FloorLamp",
  "Floor_Lamp_8": "FloorLamp",
  "Floor_Lamp_9": "FloorLamp",
  "RoboTHOR_floor_lamp_holmo_v": "FloorLamp",
  "RoboTHOR_floor_lamp_not_v": "FloorLamp",
  "Footstool_1": "Footstool",
  "Footstool_1_1_1": "Footstool",
  "Footstool_1_2_1": "Footstool",
  "Footstool_2": "Footstool",
  "Footstool_2_1": "Footstool",
  "Footstool_3": "Footstool",
  "Footstool_4": "Footstool",
  "Fork_1": "Fork",
  "RoboTHOR_fork_ai2_v": "Fork",
  "Fridge_1": "Fridge",
  "Fridge_10": "Fridge",
  "Fridge_11": "Fridge",
  "Fridge_12": "Fridge",
  "Fridge_13": "Fridge",
  "Fridge_14": "Fridge",
  "Fridge_15": "Fridge",
  "Fridge_16": "Fridge",
  "Fridge_17": "Fridge",
  "Fridge_18": "Fridge",
  "Fridge_19": "Fridge",
  "Fridge_2": "Fridge",
  "Fridge_20": "Fridge",
  "Fridge_21": "Fridge",
  "Fridge_22": "Fridge",
  "Fridge_23": "Fridge",
  "Fridge_24": "Fridge",
  "Fridge_25": "Fridge",
  "Fridge_26": "Fridge",
  "Fridge_27": "Fridge",
  "Fridge_28": "Fridge",
  "Fridge_29": "Fridge",
  "Fridge_3": "Fridge",
  "Fridge_30": "Fridge",
  "Fridge_4": "Fridge",
  "Fridge_5": "Fridge",
  "Fridge_6": "Fridge",
  "Fridge_7": "Fridge",
  "Fridge_8": "Fridge",
  "Fridge_9": "Fridge",
  "GarbageBag_21_1": "GarbageBag",
  "GarbageBag_21_2": "GarbageBag",
  "RoboTHOR_garbage_bin_ai2_1_v": "GarbageCan",
  "bin_1": "GarbageCan",
  "bin_10": "GarbageCan",
  "bin_11": "GarbageCan",
  "bin_12": "GarbageCan",
  "bin_13": "GarbageCan",
  "bin_14": "GarbageCan",
  "bin_15": "GarbageCan",
  "bin_16": "GarbageCan",
  "bin_17": "GarbageCan",
  "bin_18": "GarbageCan",
  "bin_19": "GarbageCan",
  "bin_2": "GarbageCan",
  "bin_20": "GarbageCan",
  "bin_21": "GarbageCan",
  "bin_22": "GarbageCan",
  "bin_23": "GarbageCan",
  "bin_24": "GarbageCan",
  "bin_25": "GarbageCan",
  "bin_26": "GarbageCan",
  "bin_27": "GarbageCan",
  "bin_28": "GarbageCan",
  "bin_29": "GarbageCan",
  "bin_3": "GarbageCan",
  "bin_30": "GarbageCan",
  "bin_4": "GarbageCan",
  "bin_5": "GarbageCan",
  "bin_6": "GarbageCan",
  "bin_7": "GarbageCan",
  "bin_8": "GarbageCan",
  "bin_9": "GarbageCan",
  "Hand_Towel_1": "HandTowel",
  "Hand_Towel_Holder1": "HandTowelHolder",
  "Houseplant_1": "HousePlant",
  "Houseplant_10": "HousePlant",
  "Houseplant_11": "HousePlant",
  "Houseplant_12": "HousePlant",
  "Houseplant_13": "HousePlant",
  "Houseplant_14": "HousePlant",
  "Houseplant_15": "HousePlant",
  "Houseplant_16": "HousePlant",
  "Houseplant_17": "HousePlant",
  "Houseplant_18": "HousePlant",
  "Houseplant_19": "HousePlant",
  "Houseplant_2": "HousePlant",
  "Houseplant_20": "HousePlant",
  "Houseplant_21": "HousePlant",
  "Houseplant_22": "HousePlant",
  "Houseplant_23": "HousePlant",
  "Houseplant_24": "HousePlant",
  "Houseplant_25": "HousePlant",
  "Houseplant_26": "HousePlant",
  "Houseplant_27": "HousePlant",
  "Houseplant_28": "HousePlant",
  "Houseplant_29": "HousePlant",
  "Houseplant_3": "HousePlant",
  "Houseplant_30": "HousePlant",
  "Houseplant_4": "HousePlant",
  "Houseplant_5": "HousePlant",
  "Houseplant_6": "HousePlant",
  "Houseplant_7": "HousePlant",
  "Houseplant_8": "HousePlant",
  "Houseplant_9": "HousePlant",
  "RoboTHOR_houseplant_ai2_2_v": "HousePlant",
  "Kettle_1": "Kettle",
  "Keychain_1": "KeyChain",
  "Keychain_2": "KeyChain",
  "Keychain_3": "KeyChain",
  "Knife_1": "Knife",
  "Knife_2": "Knife",
  "Knife_3": "Knife",
  "Knife_4": "Knife",
  "Knife_5": "Knife",
  "Knife_6": "Knife",
  "Knife_7": "Knife",
  "Ladle_1": "Ladle",
  "Ladle_2": "Ladle",
  "Ladle_3": "Ladle",
  "Laptop_1": "Laptop",
  "Laptop_10": "Laptop",
  "Laptop_11": "Laptop",
  "Laptop_12": "Laptop",
  "Laptop_13": "Laptop",
  "Laptop_14": "Laptop",
  "Laptop_15": "Laptop",
  "Laptop_16": "Laptop",
  "Laptop_17": "Laptop",
  "Laptop_18": "Laptop",
  "Laptop_19": "Laptop",
  "Laptop_2": "Laptop",
  "Laptop_20": "Laptop",
  "Laptop_21": "Laptop",
  "Laptop_22": "Laptop",
  "Laptop_23": "Laptop",
  "Laptop_24": "Laptop",
  "Laptop_25": "Laptop",
  "Laptop_26": "Laptop",
  "Laptop_27": "Laptop",
  "Laptop_28": "Laptop",
  "Laptop_29": "Laptop",
  "Laptop_3": "Laptop",
  "Laptop_30": "Laptop",
  "Laptop_4": "Laptop",
  "Laptop_5": "Laptop",
  "Laptop_6": "Laptop",
  "Laptop_7": "Laptop",
  "Laptop_8": "Laptop",
  "Laptop_9": "Laptop",
  "RoboTHOR_laptop_props_america_1_v": "Laptop",
  "Laundry_Hamper_1_1": "LaundryHamper",
  "Laundry_Hamper_1_2": "LaundryHamper",
  "Laundry_Hamper_1_3": "LaundryHamper",
  "Laundry_Hamper_1_4": "LaundryHamper",
  "Lettuce_1": "Lettuce",
  "Lettuce_10": "Lettuce",
  "Lettuce_11": "Lettuce",
  "Lettuce_12": "Lettuce",
  "Lettuce_13": "Lettuce",
  "Lettuce_14": "Lettuce",
  "Lettuce_15": "Lettuce",
  "Lettuce_16": "Lettuce",
  "Lettuce_17": "Lettuce",
  "Lettuce_18": "Lettuce",
  "Lettuce_19": "Lettuce",
  "Lettuce_2": "Lettuce",
  "Lettuce_20": "Lettuce",
  "Lettuce_21": "Lettuce",
  "Lettuce_22": "Lettuce",
  "Lettuce_23": "Lettuce",
  "Lettuce_24": "Lettuce",
  "Lettuce_25": "Lettuce",
  "Lettuce_26": "Lettuce",
  "Lettuce_27": "Lettuce",
  "Lettuce_28": "Lettuce",
  "Lettuce_29": "Lettuce",
  "Lettuce_3": "Lettuce",
  "Lettuce_30": "Lettuce",
  "Lettuce_4": "Lettuce",
  "Lettuce_5": "Lettuce",
  "Lettuce_6": "Lettuce",
  "Lettuce_7": "Lettuce",
  "Lettuce_8": "Lettuce",
  "Lettuce_9": "Lettuce",
  "Light_Switch_1": "LightSwitch",
  "Light_Switch_10": "LightSwitch",
  "Light_Switch_11": "LightSwitch",
  "Light_Switch_12": "LightSwitch",
  "Light_Switch_13": "LightSwitch",
  "Light_Switch_14": "LightSwitch",
  "Light_Switch_15": "LightSwitch",
  "Light_Switch_16": "LightSwitch",
  "Light_Switch_17": "LightSwitch",
  "Light_Switch_18": "LightSwitch",
  "Light_Switch_19": "LightSwitch",
  "Light_Switch_2": "LightSwitch",
  "Light_Switch_20": "LightSwitch",
  "Light_Switch_21": "LightSwitch",
  "Light_Switch_22": "LightSwitch",
  "Light_Switch_23": "LightSwitch",
  "Light_Switch_24": "LightSwitch",
  "Light_Switch_25": "LightSwitch",
  "Light_Switch_26": "LightSwitch",
  "Light_Switch_27": "LightSwitch",
  "Light_Switch_28": "LightSwitch",
  "Light_Switch_29": "LightSwitch",
  "Light_Switch_3": "LightSwitch",
  "Light_Switch_30": "LightSwitch",
  "Light_Switch_4": "LightSwitch",
  "Light_Switch_5": "LightSwitch",
  "Light_Switch_6": "LightSwitch",
  "Light_Switch_7": "LightSwitch",
  "Light_Switch_8": "LightSwitch",
  "Light_Switch_9": "LightSwitch",
  "Microwave_1": "Microwave",
  "Microwave_10": "Microwave",
  "Microwave_11": "Microwave",
  "Microwave_12": "Microwave",
  "Microwave_13": "Microwave",
  "Microwave_14": "Microwave",
  "Microwave_15": "Microwave",
  "Microwave_16": "Microwave",
  "Microwave_17": "Microwave",
  "Microwave_18": "Microwave",
  "Microwave_19": "Microwave",
  "Microwave_2": "Microwave",
  "Microwave_20": "Microwave",
  "Microwave_21": "Microwave",
  "Microwave_22": "Microwave",
  "Microwave_23": "Microwave",
  "Microwave_24": "Microwave",
  "Microwave_25": "Microwave",
  "Microwave_26": "Microwave",
  "Microwave_27": "Microwave",
  "Microwave_28": "Microwave",
  "Microwave_29": "Microwave",
  "Microwave_3": "Microwave",
  "Microwave_30": "Microwave",
  "Microwave_4": "Microwave",
  "Microwave_5": "Microwave",
  "Microwave_6": "Microwave",
  "Microwave_7": "Microwave",
  "Microwave_8": "Microwave",
  "Microwave_9": "Microwave",
  "Mug_1": "Mug",
  "Mug_2": "Mug",
  "Mug_3": "Mug",
  "RoboTHOR_mug_ai2_1_v": "Mug",
  "RoboTHOR_mug_ai2_2_v": "Mug",
  "Newspaper_1": "Newspaper",
  "Newspaper_2": "Newspaper",
  "Newspaper_3": "Newspaper",
  "Newspaper_4": "Newspaper",
  "Newspaper_5": "Newspaper",
  "Ottoman_203_1": "Ottoman",
  "Ottoman_205_1": "Ottoman",
  "Ottoman_208_1": "Ottoman",
  "Ottoman_210_1": "Ottoman",
  "Wall_Decor_Painting_1": "Painting",
  "Wall_Decor_Painting_10": "Painting",
  "Wall_Decor_Painting_1V": "Painting",
  "Wall_Decor_Painting_2": "Painting",
  "Wall_Decor_Painting_2V": "Painting",
  "Wall_Decor_Painting_3": "Painting",
  "Wall_Decor_Painting_3V": "Painting",
  "Wall_Decor_Painting_4": "Painting",
  "Wall_Decor_Painting_5": "Painting",
  "Wall_Decor_Painting_6": "Painting",
  "Wall_Decor_Painting_7": "Painting",
  "Wall_Decor_Painting_8": "Painting",
  "Wall_Decor_Painting_9": "Painting",
  "Wall_Decor_Photo_1": "Painting",
  "Wall_Decor_Photo_10": "Painting",
  "Wall_Decor_Photo_1V": "Painting",
  "Wall_Decor_Photo_2": "Painting",
  "Wall_Decor_Photo_2V": "Painting",
  "Wall_Decor_Photo_3": "Painting",
  "Wall_Decor_Photo_3V": "Painting",
  "Wall_Decor_Photo_4": "Painting",
  "Wall_Decor_Photo_5": "Painting",
  "Wall_Decor_Photo_6": "Painting",
  "Wall_Decor_Photo_7": "Painting",
  "Wall_Decor_Photo_8": "Painting",
  "Wall_Decor_Photo_9": "Painting",
  "Pan_1": "Pan",
  "Pan_10": "Pan",
  "Pan_11": "Pan",
  "Pan_12": "Pan",
  "Pan_13": "Pan",
  "Pan_14": "Pan",
  "Pan_15": "Pan",
  "Pan_16": "Pan",
  "Pan_17": "Pan",
  "Pan_18": "Pan",
  "Pan_19": "Pan",
  "Pan_2": "Pan",
  "Pan_20": "Pan",
  "Pan_21": "Pan",
  "Pan_22": "Pan",
  "Pan_23": "Pan",
  "Pan_24": "Pan",
  "Pan_25": "Pan",
  "Pan_26": "Pan",
  "Pan_27": "Pan",
  "Pan_28": "Pan",
  "Pan_29": "Pan",
  "Pan_3": "Pan",
  "Pan_30": "Pan",
  "Pan_4": "Pan",
  "Pan_5": "Pan",
  "Pan_6": "Pan",
  "Pan_7": "Pan",
  "Pan_8": "Pan",
  "Pan_9": "Pan",
  "Paper_Towel_1": "PaperTowelRoll",
  "Pen_1": "Pen",
  "Pen_2": "Pen",
  "Pen_3": "Pen",
  "Pen_4": "Pen",
  "RoboTHOR_pen_signo_v": "Pen",
  "Pencil_1": "Pencil",
  "Pencil_2": "Pencil",
  "Pencil_3": "Pencil",
  "Pencil_4": "Pencil",
  "Pencil_5": "Pencil",
  "Pencil_6": "Pencil",
  "Pencil_7": "Pencil",
  "RoboTHOR_pencil_amazon_basics_v": "Pencil",
  "Pepper_Shaker_1": "PepperShaker",
  "Pepper_Shaker_2": "PepperShaker",
  "RoboTHOR_salt_pepper_shaker_bnyd_pepper_v": "PepperShaker",
  "RoboTHOR_pillow_dvala_v": "Pillow",
  "RoboTHOR_pillow_sanglarka_1_v": "Pillow",
  "pillow_1": "Pillow",
  "pillow_10": "Pillow",
  "pillow_11": "Pillow",
  "pillow_12": "Pillow",
  "pillow_13": "Pillow",
  "pillow_14": "Pillow",
  "pillow_15": "Pillow",
  "pillow_16": "Pillow",
  "pillow_17": "Pillow",
  "pillow_18": "Pillow",
  "pillow_19": "Pillow",
  "pillow_2": "Pillow",
  "pillow_20": "Pillow",
  "pillow_21": "Pillow",
  "pillow_22": "Pillow",
  "pillow_23": "Pillow",
  "pillow_24": "Pillow",
  "pillow_25": "Pillow",
  "pillow_26": "Pillow",
  "pillow_27": "Pillow",
  "pillow_28": "Pillow",
  "pillow_29": "Pillow",
  "pillow_3": "Pillow",
  "pillow_30": "Pillow",
  "pillow_4": "Pillow",
  "pillow_5": "Pillow",
  "pillow_6": "Pillow",
  "pillow_7": "Pillow",
  "pillow_8": "Pillow",
  "pillow_9": "Pillow",
  "Plate_1": "Plate",
  "Plate_10": "Plate",
  "Plate_11": "Plate",
  "Plate_12": "Plate",
  "Plate_13": "Plate",
  "Plate_14": "Plate",
  "Plate_15": "Plate",
  "Plate_16": "Plate",
  "Plate_17": "Plate",
  "Plate_18": "Plate",
  "Plate_19": "Plate",
  "Plate_2": "Plate",
  "Plate_20": "Plate",
  "Plate_21": "Plate",
  "Plate_22": "Plate",
  "Plate_23": "Plate",
  "Plate_24": "Plate",
  "Plate_25": "Plate",
  "Plate_26": "Plate",
  "Plate_27": "Plate",
  "Plate_28": "Plate",
  "Plate_29": "Plate",
  "Plate_3": "Plate",
  "Plate_30": "Plate",
  "Plate_4": "Plate",
  "Plate_5": "Plate",
  "Plate_6": "Plate",
  "Plate_7": "Plate",
  "Plate_8": "Plate",
  "Plate_9": "Plate",
  "RoboTHOR_plate_ai2_v": "Plate",
  "Plunger_1": "Plunger",
  "Plunger_2": "Plunger",
  "Plunger_3": "Plunger",
  "Pot_1": "Pot",
  "Pot_10": "Pot",
  "Pot_11": "Pot",
  "Pot_12": "Pot",
  "Pot_13": "Pot",
  "Pot_14": "Pot",
  "Pot_15": "Pot",
  "Pot_16": "Pot",
  "Pot_17": "Pot",
  "Pot_18": "Pot",
  "Pot_19": "Pot",
  "Pot_2": "Pot",
  "Pot_20": "Pot",
  "Pot_21": "Pot",
  "Pot_22": "Pot",
  "Pot_23": "Pot",
  "Pot_24": "Pot",
  "Pot_25": "Pot",
  "Pot_26": "Pot",
  "Pot_27": "Pot",
  "Pot_28": "Pot",
  "Pot_29": "Pot",
  "Pot_3": "Pot",
  "Pot_30": "Pot",
  "Pot_4": "Pot",
  "Pot_5": "Pot",
  "Pot_6": "Pot",
  "Pot_7": "Pot",
  "Pot_8": "Pot",
  "Pot_9": "Pot",
  "Potato_1": "Potato",
  "Potato_10": "Potato",
  "Potato_11": "Potato",
  "Potato_12": "Potato",
  "Potato_13": "Potato",
  "Potato_14": "Potato",
  "Potato_15": "Potato",
  "Potato_16": "Potato",
  "Potato_17": "Potato",
  "Potato_18": "Potato",
  "Potato_19": "Potato",
  "Potato_2": "Potato",
  "Potato_20": "Potato",
  "Potato_21": "Potato",
  "Potato_22": "Potato",
  "Potato_23": "Potato",
  "Potato_24": "Potato",
  "Potato_25": "Potato",
  "Potato_26": "Potato",
  "Potato_27": "Potato",
  "Potato_28": "Potato",
  "Potato_29": "Potato",
  "Potato_3": "Potato",
  "Potato_30": "Potato",
  "Potato_4": "Potato",
  "Potato_5": "Potato",
  "Potato_6": "Potato",
  "Potato_7": "Potato",
  "Potato_8": "Potato",
  "Potato_9": "Potato",
  "Remote_1": "RemoteControl",
  "Remote_2": "RemoteControl",
  "Remote_3": "RemoteControl",
  "RoboTHOR_remote_coolux_v": "RemoteControl",
  "Room_Decor_1_1": "RoomDecor",
  "Room_Decor_1_2": "RoomDecor",
  "Safe_18_1": "Safe",
  "Safe_18_2": "Safe",
  "RoboTHOR_salt_pepper_shaker_bnyd_salt_v": "SaltShaker",
  "Salt_Shaker_1": "SaltShaker",
  "Salt_Shaker_2": "SaltShaker",
  "Scrub_Brush_1": "ScrubBrush",
  "RoboTHOR_shelving_unit_kallax_large": "ShelvingUnit",
  "RoboTHOR_shelving_unit_kallax_small_2_v": "ShelvingUnit",
  "Shelving_Unit_001_1": "ShelvingUnit",
  "Shelving_Unit_206_1": "ShelvingUnit",
  "Shelving_Unit_206_2": "ShelvingUnit",
  "Shelving_Unit_215_1": "ShelvingUnit",
  "Shelving_Unit_219_1": "ShelvingUnit",
  "Shelving_Unit_303_1": "ShelvingUnit",
  "Shelving_Unit_307_1": "ShelvingUnit",
  "Shelving_Unit_313_1": "ShelvingUnit",
  "Shelving_Unit_319_1": "ShelvingUnit",
  "Shelving_Unit_324_1": "ShelvingUnit",
  "Shelving_Unit_325_1": "ShelvingUnit",
  "Shelving_Unit_325_2": "ShelvingUnit",
  "Shower_Curtain_1": "ShowerCurtain",
  "Shower_Curtain_2": "ShowerCurtain",
  "Shower_Head_1": "ShowerHead",
  "Shower_Head_2": "ShowerHead",
  "RoboTHOR_side_table_fornbro": "SideTable",
  "RoboTHOR_side_table_havsta_v": "SideTable",
  "RoboTHOR_side_table_hol": "SideTable",
  "RoboTHOR_side_table_hopen": "SideTable",
  "RoboTHOR_side_table_nested_havsta_v": "SideTable",
  "RoboTHOR_side_table_strind": "SideTable",
  "RoboTHOR_side_table_tingby": "SideTable",
  "Side_Table_201_1_1": "SideTable",
  "Side_Table_201_2_1": "SideTable",
  "Side_Table_201_3_1": "SideTable",
  "Side_Table_202_1": "SideTable",
  "Side_Table_203_1": "SideTable",
  "Side_Table_203_2": "SideTable",
  "Side_Table_203_3": "SideTable",
  "Side_Table_205_1_1": "SideTable",
  "Side_Table_205_2_1": "SideTable",
  "Side_Table_205_2_2": "SideTable",
  "Side_Table_207_1": "SideTable",
  "Side_Table_209_1_1": "SideTable",
  "Side_Table_209_2_1": "SideTable",
  "Side_Table_210_1_1": "SideTable",
  "Side_Table_210_2_1": "SideTable",
  "Side_Table_213_1_1": "SideTable",
  "Side_Table_213_2_1": "SideTable",
  "Side_Table_213_3_1": "SideTable",
  "Side_Table_213_4_1": "SideTable",
  "Side_Table_214_1": "SideTable",
  "Side_Table_215_1": "SideTable",
  "Side_Table_216_1_1": "SideTable",
  "Side_Table_216_2_1": "SideTable",
  "Side_Table_216_3_1": "SideTable",
  "Side_Table_217_1": "SideTable",
  "Side_Table_218_1": "SideTable",
  "Side_Table_219_1": "SideTable",
  "Side_Table_21_1": "SideTable",
  "Side_Table_220_1": "SideTable",
  "Side_Table_220_2": "SideTable",
  "Side_Table_222_1_1": "SideTable",
  "Side_Table_222_2_1": "SideTable",
  "Side_Table_223_1": "SideTable",
  "Side_Table_223_2": "SideTable",
  "Side_Table_224_1": "SideTable",
  "Side_Table_225_1": "SideTable",
  "Side_Table_228_1_1": "SideTable",
  "Side_Table_228_2_1": "SideTable",
  "Side_Table_229_1_1": "SideTable",
  "Side_Table_229_2_1": "SideTable",
  "Side_Table_230_1": "SideTable",
  "Side_Table_302_1_1": "SideTable",
  "Side_Table_302_1_2": "SideTable",
  "Side_Table_302_1_3": "SideTable",
  "Side_Table_302_1_4": "SideTable",
  "Side_Table_302_1_5": "SideTable",
  "Side_Table_302_1_6": "SideTable",
  "Side_Table_302_1_7": "SideTable",
  "Side_Table_302_2_1": "SideTable",
  "Side_Table_303_1_1": "SideTable",
  "Side_Table_303_2_1": "SideTable",
  "Side_Table_305_1": "SideTable",
  "Side_Table_306_1": "SideTable",
  "Side_Table_306_2": "SideTable",
  "Side_Table_307_1": "SideTable",
  "Side_Table_309_1": "SideTable",
  "Side_Table_310_1": "SideTable",
  "Side_Table_311_1_1": "SideTable",
  "Side_Table_311_2_1": "SideTable",
  "Side_Table_311_2_2": "SideTable",
  "Side_Table_313_1": "SideTable",
  "Side_Table_317_1": "SideTable",
  "Side_Table_320_1": "SideTable",
  "Side_Table_322_1": "SideTable",
  "Side_Table_329_1": "SideTable",
  "Side_Table_3_1": "SideTable",
  "Side_Table_401_1": "SideTable",
  "Sink_1": "Sink",
  "Sink_10": "Sink",
  "Sink_11": "Sink",
  "Sink_12": "Sink",
  "Sink_13": "Sink",
  "Sink_14": "Sink",
  "Sink_15": "Sink",
  "Sink_16": "Sink",
  "Sink_17": "Sink",
  "Sink_18": "Sink",
  "Sink_19": "Sink",
  "Sink_2": "Sink",
  "Sink_20": "Sink",
  "Sink_21": "Sink",
  "Sink_22": "Sink",
  "Sink_23": "Sink",
  "Sink_24": "Sink",
  "Sink_25": "Sink",
  "Sink_26": "Sink",
  "Sink_27": "Sink",
  "Sink_28": "Sink",
  "Sink_29": "Sink",
  "Sink_3": "Sink",
  "Sink_30": "Sink",
  "Sink_4": "Sink",
  "Sink_5": "Sink",
  "Sink_6": "Sink",
  "Sink_7": "Sink",
  "Sink_8": "Sink",
  "Sink_9": "Sink",
  "Soap_Bar_1": "SoapBar",
  "Soap_Bottle_1": "SoapBottle",
  "Soap_Bottle_10": "SoapBottle",
  "Soap_Bottle_11": "SoapBottle",
  "Soap_Bottle_12": "SoapBottle",
  "Soap_Bottle_13": "SoapBottle",
  "Soap_Bottle_14": "SoapBottle",
  "Soap_Bottle_15": "SoapBottle",
  "Soap_Bottle_16": "SoapBottle",
  "Soap_Bottle_17": "SoapBottle",
  "Soap_Bottle_18": "SoapBottle",
  "Soap_Bottle_19": "SoapBottle",
  "Soap_Bottle_2": "SoapBottle",
  "Soap_Bottle_20": "SoapBottle",
  "Soap_Bottle_21": "SoapBottle",
  "Soap_Bottle_22": "SoapBottle",
  "Soap_Bottle_23": "SoapBottle",
  "Soap_Bottle_24": "SoapBottle",
  "Soap_Bottle_25": "SoapBottle",
  "Soap_Bottle_26": "SoapBottle",
  "Soap_Bottle_27": "SoapBottle",
  "Soap_Bottle_28": "SoapBottle",
  "Soap_Bottle_29": "SoapBottle",
  "Soap_Bottle_3": "SoapBottle",
  "Soap_Bottle_30": "SoapBottle",
  "Soap_Bottle_4": "SoapBottle",
  "Soap_Bottle_5": "SoapBottle",
  "Soap_Bottle_6": "SoapBottle",
  "Soap_Bottle_7": "SoapBottle",
  "Soap_Bottle_8": "SoapBottle",
  "Soap_Bottle_9": "SoapBottle",
  "RoboTHOR_sofa_alrid": "Sofa",
  "RoboTHOR_sofa_ektorp_v": "Sofa",
  "RoboTHOR_sofa_kramfors": "Sofa",
  "RoboTHOR_sofa_solsta": "Sofa",
  "RoboTHOR_sofa_vreta": "Sofa",
  "Sofa_201_1": "Sofa",
  "Sofa_201_2": "Sofa",
  "Sofa_201_3": "Sofa",
  "Sofa_201_4": "Sofa",
  "Sofa_203_1": "Sofa",
  "Sofa_204_1": "Sofa",
  "Sofa_205_1": "Sofa",
  "Sofa_205_2": "Sofa",
  "Sofa_206_1": "Sofa",
  "Sofa_207_1": "Sofa",
  "Sofa_207_2": "Sofa",
  "Sofa_207_3": "Sofa",
  "Sofa_207_4": "Sofa",
  "Sofa_207_5": "Sofa",
  "Sofa_208_1": "Sofa",
  "Sofa_210_1": "Sofa",
  "Sofa_213_1": "Sofa",
  "Sofa_214_1": "Sofa",
  "Sofa_214_2": "Sofa",
  "Sofa_215_1": "Sofa",
  "Sofa_216_1": "Sofa",
  "Sofa_216_2": "Sofa",
  "Sofa_216_3": "Sofa",
  "Sofa_216_4": "Sofa",
  "Sofa_218_1": "Sofa",
  "Sofa_218_2": "Sofa",
  "Sofa_220_1": "Sofa",
  "Sofa_221_1": "Sofa",
  "Sofa_223_1": "Sofa",
  "Sofa_223_2": "Sofa",
  "Sofa_223_3": "Sofa",
  "Sofa_227_1": "Sofa",
  "Spatula_1": "Spatula",
  "Spoon_1": "Spoon",
  "RoboTHOR_spray_bottle_kramig_v": "SprayBottle",
  "Spray_Bottle_1": "SprayBottle",
  "Spray_Bottle_2": "SprayBottle",
  "Spray_Bottle_3": "SprayBottle",
  "Spray_Bottle_4": "SprayBottle",
  "Spray_Bottle_5": "SprayBottle",
  "Spray_Bottle_6": "SprayBottle",
  "Spray_Bottle_7": "SprayBottle",
  "Spray_Bottle_8": "SprayBottle",
  "Dog_Statue_1": "Statue",
  "Dog_Statue_2": "Statue",
  "Dog_Statue_3": "Statue",
  "Dog_Statue_4": "Statue",
  "Fertility_Statue_1": "Statue",
  "Fertility_Statue_2": "Statue",
  "Fertility_Statue_3": "Statue",
  "Hand_Statue_1": "Statue",
  "Hand_Statue_2": "Statue",
  "Hand_Statue_3": "Statue",
  "Stone_Statue_1": "Statue",
  "Stone_Statue_2": "Statue",
  "Stone_Statue_3": "Statue",
  "Stone_Statue_4": "Statue",
  "Towel_Statue_1": "Statue",
  "Towel_Statue_2": "Statue",
  "Towel_Statue_3": "Statue",
  "Waving_Statue_1": "Statue",
  "Waving_Statue_2": "Statue",
  "Waving_Statue_3": "Statue",
  "Stool_1_1": "Stool",
  "Stool_1_2": "Stool",
  "Stool_1_3": "Stool",
  "Stool_2_1": "Stool",
  "Stool_2_2": "Stool",
  "Stool_2_3": "Stool",
  "Stool_2_4": "Stool",
  "Stool_3_1": "Stool",
  "Stool_4_1": "Stool",
  "Stool_5_1": "Stool",
  "TV_Stand_201_1": "TVStand",
  "TV_Stand_202_1": "TVStand",
  "TV_Stand_204_1": "TVStand",
  "TV_Stand_206_1": "TVStand",
  "TV_Stand_206_2": "TVStand",
  "TV_Stand_206_3": "TVStand",
  "TV_Stand_211_1": "TVStand",
  "TV_Stand_212_1": "TVStand",
  "TV_Stand_220_1": "TVStand",
  "TV_Stand_222_1": "TVStand",
  "TV_Stand_223_1": "TVStand",
  "Tabletop_Decor_1_1": "TableTopDecor",
  "Teddy_Bear_1": "TeddyBear",
  "Teddy_Bear_2": "TeddyBear",
  "RoboTHOR_television_props_america_1_v": "Television",
  "Television_1": "Television",
  "Television_10": "Television",
  "Television_11": "Television",
  "Television_12": "Television",
  "Television_13": "Television",
  "Television_14": "Television",
  "Television_15": "Television",
  "Television_16": "Television",
  "Television_17": "Television",
  "Television_18": "Television",
  "Television_19": "Television",
  "Television_2": "Television",
  "Television_20": "Television",
  "Television_21": "Television",
  "Television_22": "Television",
  "Television_23": "Television",
  "Television_24": "Television",
  "Television_25": "Television",
  "Television_26": "Television",
  "Television_27": "Television",
  "Television_28": "Television",
  "Television_29": "Television",
  "Television_2_1": "Television",
  "Television_3": "Television",
  "Television_30": "Television",
  "Television_4": "Television",
  "Television_5": "Television",
  "Television_6": "Television",
  "Television_7": "Television",
  "Television_8": "Television",
  "Television_9": "Television",
  "RoboTHOR_tennis_racquet_speed_kids_v": "TennisRacket",
  "Tennis_Racquet_1": "TennisRacket",
  "Tennis_Racquet_2": "TennisRacket",
  "Tennis_Racquet_3": "TennisRacket",
  "Tennis_Racquet_4": "TennisRacket",
  "Tennis_Racquet_5": "TennisRacket",
  "Tissue_Box_1": "TissueBox",
  "Toaster_1": "Toaster",
  "Toaster_10": "Toaster",
  "Toaster_11": "Toaster",
  "Toaster_12": "Toaster",
  "Toaster_13": "Toaster",
  "Toaster_14": "Toaster",
  "Toaster_15": "Toaster",
  "Toaster_16": "Toaster",
  "Toaster_17": "Toaster",
  "Toaster_18": "Toaster",
  "Toaster_19": "Toaster",
  "Toaster_2": "Toaster",
  "Toaster_20": "Toaster",
  "Toaster_21": "Toaster",
  "Toaster_22": "Toaster",
  "Toaster_23": "Toaster",
  "Toaster_24": "Toaster",
  "Toaster_25": "Toaster",
  "Toaster_26": "Toaster",
  "Toaster_27": "Toaster",
  "Toaster_28": "Toaster",
  "Toaster_29": "Toaster",
  "Toaster_3": "Toaster",
  "Toaster_30": "Toaster",
  "Toaster_4": "Toaster",
  "Toaster_5": "Toaster",
  "Toaster_6": "Toaster",
  "Toaster_7": "Toaster",
  "Toaster_8": "Toaster",
  "Toaster_9": "Toaster",
  "Toilet_1": "Toilet",
  "Toilet_2": "Toilet",
  "Toilet_Paper": "ToiletPaper",
  "Toilet_Paper_Used_Up": "ToiletPaper",
  "Toilet_Paper_Hanger_1": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_10": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_11": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_12": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_13": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_14": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_15": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_16": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_17": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_18": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_19": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_2": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_20": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_21": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_22": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_23": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_24": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_25": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_26": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_27": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_28": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_29": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_3": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_30": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_4": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_5": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_6": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_7": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_8": "ToiletPaperHanger",
  "Toilet_Paper_Hanger_9": "ToiletPaperHanger",
  "Tomato_1": "Tomato",
  "Tomato_10": "Tomato",
  "Tomato_11": "Tomato",
  "Tomato_12": "Tomato",
  "Tomato_13": "Tomato",
  "Tomato_14": "Tomato",
  "Tomato_15": "Tomato",
  "Tomato_16": "Tomato",
  "Tomato_17": "Tomato",
  "Tomato_18": "Tomato",
  "Tomato_19": "Tomato",
  "Tomato_2": "Tomato",
  "Tomato_20": "Tomato",
  "Tomato_21": "Tomato",
  "Tomato_22": "Tomato",
  "Tomato_23": "Tomato",
  "Tomato_24": "Tomato",
  "Tomato_25": "Tomato",
  "Tomato_26": "Tomato",
  "Tomato_27": "Tomato",
  "Tomato_28": "Tomato",
  "Tomato_29": "Tomato",
  "Tomato_3": "Tomato",
  "Tomato_30": "Tomato",
  "Tomato_4": "Tomato",
  "Tomato_5": "Tomato",
  "Tomato_6": "Tomato",
  "Tomato_7": "Tomato",
  "Tomato_8": "Tomato",
  "Tomato_9": "Tomato",
  "Bath_Towel_1": "Towel",
  "Bath_Towel_2": "Towel",
  "Bath_Towel_3": "Towel",
  "Bath_Towel_Holder1": "TowelHolder",
  "Vacuum_Cleaner_1_1": "VacuumCleaner",
  "RoboTHOR_vase_stilren_v": "Vase",
  "Vase_Decorative_1": "Vase",
  "Vase_Flat_1": "Vase",
  "Vase_Flat_2": "Vase",
  "Vase_Flat_3": "Vase",
  "Vase_Flat_4": "Vase",
  "Vase_Flat_5": "Vase",
  "Vase_Medium_1": "Vase",
  "Vase_Medium_2": "Vase",
  "Vase_Medium_3": "Vase",
  "Vase_Medium_4": "Vase",
  "Vase_Medium_5": "Vase",
  "Vase_Open_1": "Vase",
  "Vase_Open_2": "Vase",
  "Vase_Open_3": "Vase",
  "Vase_Tall_1": "Vase",
  "Vase_Tall_2": "Vase",
  "Vase_Tall_3": "Vase",
  "Vase_Tall_4": "Vase",
  "Vase_Tall_5": "Vase",
  "Washing_Machine_1": "WashingMachine",
  "Washing_Machine_2": "WashingMachine",
  "Watch_1": "Watch",
  "Watch_2": "Watch",
  "Watering_Can_1": "WateringCan",
  "Window_Bay_1": "Window",
  "Window_Bay_2": "Window",
  "Window_Bay_3": "Window",
  "Window_Fixed_36x48": "Window",
  "Window_Fixed_60x36": "Window",
  "Window_Fixed_60x48": "Window",
  "Window_Fixed_60x72": "Window",
  "Window_Fixed_96x48": "Window",
  "Window_Fixed_96x72": "Window",
  "Window_Hung_32x60": "Window",
  "Window_Hung_36x32": "Window",
  "Window_Hung_44x60": "Window",
  "Window_Hung_48x24": "Window",
  "Window_Hung_48x32": "Window",
  "Window_Hung_48x44": "Window",
  "Window_Slider_36x36": "Window",
  "Window_Slider_48x24": "Window",
  "Window_Slider_48x36": "Window",
  "Window_Slider_48x48": "Window",
  "Window_Slider_60x36": "Window",
  "Window_Slider_60x48": "Window",
  "Wine_Bottle_1": "WineBottle"
}

OBJECT_TO_ASSET = {
  "AlarmClock": [
    "Alarm_Clock_1",
    "Alarm_Clock_10",
    "Alarm_Clock_11",
    "Alarm_Clock_12",
    "Alarm_Clock_13",
    "Alarm_Clock_14",
    "Alarm_Clock_15",
    "Alarm_Clock_16",
    "Alarm_Clock_17",
    "Alarm_Clock_18",
    "Alarm_Clock_19",
    "Alarm_Clock_2",
    "Alarm_Clock_20",
    "Alarm_Clock_21",
    "Alarm_Clock_22",
    "Alarm_Clock_23",
    "Alarm_Clock_24",
    "Alarm_Clock_25",
    "Alarm_Clock_26",
    "Alarm_Clock_27",
    "Alarm_Clock_28",
    "Alarm_Clock_29",
    "Alarm_Clock_3",
    "Alarm_Clock_30",
    "Alarm_Clock_4",
    "Alarm_Clock_5",
    "Alarm_Clock_6",
    "Alarm_Clock_7",
    "Alarm_Clock_8",
    "Alarm_Clock_9",
    "RoboTHOR_alarm_clock_bajk_v"
  ],
  "AluminumFoil": [
    "Aluminum_Foil_1"
  ],
  "Apple": [
    "Apple_1",
    "Apple_10",
    "Apple_11",
    "Apple_12",
    "Apple_13",
    "Apple_14",
    "Apple_15",
    "Apple_16",
    "Apple_17",
    "Apple_18",
    "Apple_19",
    "Apple_2",
    "Apple_20",
    "Apple_21",
    "Apple_22",
    "Apple_23",
    "Apple_24",
    "Apple_25",
    "Apple_26",
    "Apple_27",
    "Apple_28",
    "Apple_29",
    "Apple_3",
    "Apple_30",
    "Apple_4",
    "Apple_5",
    "Apple_6",
    "Apple_7",
    "Apple_8",
    "Apple_9",
    "RoboTHOR_apple_ai2_1_v"
  ],
  "ArmChair": [
    "ArmChair_213_1",
    "ArmChair_216_1",
    "Armchair_201_1",
    "Armchair_201_2",
    "Armchair_201_3",
    "Armchair_201_4",
    "Armchair_201_5",
    "Armchair_202_1",
    "Armchair_203_1",
    "Armchair_204_1",
    "Armchair_205_1_1",
    "Armchair_205_1_2",
    "Armchair_205_2_1",
    "Armchair_207_1",
    "Armchair_207_2",
    "Armchair_207_3",
    "Armchair_207_4",
    "Armchair_208_1",
    "Armchair_208_2",
    "Armchair_208_3",
    "Armchair_208_4",
    "Armchair_208_5",
    "Armchair_210_1",
    "Armchair_217_1",
    "Armchair_219_1",
    "Armchair_219_2",
    "Armchair_220_1",
    "Armchair_222_1",
    "Armchair_225_1",
    "Armchair_226_1",
    "Armchair_227_1",
    "Armchair_230_1",
    "RoboTHOR_armchair_ekenas_v",
    "RoboTHOR_armchair_ektorp",
    "RoboTHOR_armchair_emmabo",
    "RoboTHOR_armchair_karlstad",
    "RoboTHOR_armchair_overallt",
    "RoboTHOR_armchair_tullsta"
  ],
  "BaseballBat": [
    "BaseballBat_1",
    "BaseballBat_2",
    "BaseballBat_3",
    "BaseballBat_4",
    "RoboTHOR_baseball_bat_rawlings_v"
  ],
  "BasketBall": [
    "Basketball_1",
    "RoboTHOR_basketball_rhode_island_novelty_v"
  ],
  "Bed": [
    "Bed_1",
    "Bed_10",
    "Bed_11",
    "Bed_12",
    "Bed_13",
    "Bed_14",
    "Bed_15",
    "Bed_16",
    "Bed_17",
    "Bed_18_1",
    "Bed_18_2",
    "Bed_19",
    "Bed_2",
    "Bed_20",
    "Bed_21",
    "Bed_22",
    "Bed_23",
    "Bed_24",
    "Bed_25",
    "Bed_26_1",
    "Bed_26_2",
    "Bed_27",
    "Bed_28",
    "Bed_29",
    "Bed_3",
    "Bed_30",
    "Bed_4",
    "Bed_5",
    "Bed_6",
    "Bed_7",
    "Bed_8",
    "Bed_9",
    "RoboTHOR_bed_grankulla",
    "RoboTHOR_bed_hemnes",
    "RoboTHOR_bed_kritter",
    "RoboTHOR_bed_meldal",
    "RoboTHOR_bed_tarva_v",
    "RoboTHOR_hemnes_day_bed"
  ],
  "Blinds": [
    "Blinds_1"
  ],
  "Book": [
    "Book_1",
    "Book_10",
    "Book_11",
    "Book_12",
    "Book_13",
    "Book_14",
    "Book_15",
    "Book_16",
    "Book_17",
    "Book_18",
    "Book_19",
    "Book_2",
    "Book_20",
    "Book_21",
    "Book_22",
    "Book_23",
    "Book_24",
    "Book_25",
    "Book_26",
    "Book_27",
    "Book_28",
    "Book_29",
    "Book_3",
    "Book_30",
    "Book_4",
    "Book_5",
    "Book_6",
    "Book_7",
    "Book_8",
    "Book_9",
    "RoboTHOR_book_ai2_1_v",
    "RoboTHOR_book_ai2_2_v",
    "RoboTHOR_book_ai2_3_v",
    "RoboTHOR_book_ai2_5_v",
    "RoboTHOR_book_ai2_6_v"
  ],
  "Boots": [
    "Boot_1"
  ],
  "Bottle": [
    "Bottle_1"
  ],
  "Bowl": [
    "Bowl_1",
    "Bowl_10",
    "Bowl_11",
    "Bowl_12",
    "Bowl_13",
    "Bowl_14",
    "Bowl_15",
    "Bowl_16",
    "Bowl_17",
    "Bowl_18",
    "Bowl_19",
    "Bowl_2",
    "Bowl_20",
    "Bowl_21",
    "Bowl_22",
    "Bowl_23",
    "Bowl_24",
    "Bowl_25",
    "Bowl_26",
    "Bowl_27",
    "Bowl_28",
    "Bowl_29",
    "Bowl_3",
    "Bowl_30",
    "Bowl_4",
    "Bowl_5",
    "Bowl_6",
    "Bowl_7",
    "Bowl_8",
    "Bowl_9",
    "RoboTHOR_bowl_ai2_v"
  ],
  "Box": [
    "Box_1",
    "Box_10",
    "Box_11",
    "Box_12",
    "Box_13",
    "Box_14",
    "Box_15",
    "Box_16",
    "Box_17",
    "Box_18",
    "Box_19",
    "Box_2",
    "Box_20",
    "Box_21",
    "Box_22",
    "Box_23",
    "Box_24",
    "Box_25",
    "Box_26",
    "Box_27",
    "Box_28",
    "Box_29",
    "Box_3",
    "Box_30",
    "Box_4",
    "Box_5",
    "Box_6",
    "Box_7",
    "Box_8",
    "Box_9",
    "DecorativeBox1",
    "DecorativeBox2",
    "DecorativeBox3",
    "DecorativeBox4"
  ],
  "Bread": [
    "Bread_1",
    "Bread_10",
    "Bread_11",
    "Bread_12",
    "Bread_13",
    "Bread_14",
    "Bread_15",
    "Bread_16",
    "Bread_17",
    "Bread_18",
    "Bread_19",
    "Bread_2",
    "Bread_20",
    "Bread_21",
    "Bread_22",
    "Bread_23",
    "Bread_24",
    "Bread_25",
    "Bread_26",
    "Bread_27",
    "Bread_28",
    "Bread_29",
    "Bread_3",
    "Bread_30",
    "Bread_4",
    "Bread_5",
    "Bread_6",
    "Bread_7",
    "Bread_8",
    "Bread_9"
  ],
  "ButterKnife": [
    "ButterKnife_1",
    "RoboTHOR_butter_knife_ai2_1_v"
  ],
  "CD": [
    "CD_1"
  ],
  "Candle": [
    "Candle_1",
    "Candle_2",
    "Candle_3",
    "Candle_4",
    "Candle_5",
    "Candle_6",
    "RoboTHOR_candle_glittrig_1_v",
    "RoboTHOR_candle_glittrig_2_v",
    "RoboTHOR_candle_glittrig_3_v"
  ],
  "Cart": [
    "Cart_1"
  ],
  "CellPhone": [
    "Cellphone_1",
    "Cellphone_2",
    "Cellphone_3",
    "Cellphone_4",
    "Cellphone_5",
    "Cellphone_6",
    "Cellphone_7",
    "Cellphone_8",
    "RoboTHOR_cellphone_blackberry_v"
  ],
  "Chair": [
    "Chair_002_1",
    "Chair_002_2",
    "Chair_002_3",
    "Chair_007_1",
    "Chair_007_2",
    "Chair_007_3",
    "Chair_007_4",
    "Chair_007_5",
    "Chair_201_1",
    "Chair_203_1",
    "Chair_203_2",
    "Chair_203_3",
    "Chair_204_1",
    "Chair_204_2",
    "Chair_204_3",
    "Chair_204_4",
    "Chair_204_5",
    "Chair_204_6",
    "Chair_204_7",
    "Chair_204_8",
    "Chair_205_1",
    "Chair_205_2",
    "Chair_205_3",
    "Chair_205_4",
    "Chair_205_5",
    "Chair_210_1",
    "Chair_210_2",
    "Chair_210_3",
    "Chair_215_1",
    "Chair_215_2",
    "Chair_215_3",
    "Chair_223_1",
    "Chair_224_1",
    "Chair_227_1",
    "Chair_230_1",
    "Chair_303_1",
    "Chair_303_2",
    "Chair_304_1",
    "Chair_305_1",
    "Chair_307_1",
    "Chair_307_2",
    "Chair_311_1",
    "Chair_313_1",
    "Chair_318_1",
    "RoboTHOR_chair_antnas",
    "RoboTHOR_chair_extendable",
    "RoboTHOR_chair_jokkmokk_v",
    "RoboTHOR_chair_liatorp",
    "RoboTHOR_chair_mella",
    "RoboTHOR_chair_norden_gateleg",
    "RoboTHOR_office_chair_allak",
    "RoboTHOR_office_chair_jules",
    "RoboTHOR_office_chair_molte_v",
    "RoboTHOR_office_chair_sevnning",
    "RoboTHOR_office_chair_skruvsta",
    "RoboTHOR_office_chair_volmar"
  ],
  "Cloth": [
    "Cloth_1",
    "Cloth_10",
    "Cloth_11",
    "Cloth_12",
    "Cloth_2",
    "Cloth_3",
    "Cloth_4",
    "Cloth_5",
    "Cloth_6",
    "Cloth_7",
    "Cloth_8",
    "Cloth_9"
  ],
  "ClothesDryer": [
    "Clothes_Dryer_1",
    "Clothes_Dryer_2"
  ],
  "CoffeeMachine": [
    "coffee_machine_1",
    "coffee_machine_10",
    "coffee_machine_11",
    "coffee_machine_12",
    "coffee_machine_13",
    "coffee_machine_14",
    "coffee_machine_15",
    "coffee_machine_16",
    "coffee_machine_17",
    "coffee_machine_18",
    "coffee_machine_19",
    "coffee_machine_2",
    "coffee_machine_20",
    "coffee_machine_21",
    "coffee_machine_22",
    "coffee_machine_23",
    "coffee_machine_24",
    "coffee_machine_25",
    "coffee_machine_26",
    "coffee_machine_27",
    "coffee_machine_28",
    "coffee_machine_29",
    "coffee_machine_3",
    "coffee_machine_30",
    "coffee_machine_4",
    "coffee_machine_5",
    "coffee_machine_6",
    "coffee_machine_7",
    "coffee_machine_8",
    "coffee_machine_9"
  ],
  "CoffeeTable": [
    "Coffee_Table_201_1",
    "Coffee_Table_202_1",
    "Coffee_Table_202_2",
    "Coffee_Table_203_1",
    "Coffee_Table_204_1",
    "Coffee_Table_206_1",
    "Coffee_Table_206_2",
    "Coffee_Table_206_3",
    "Coffee_Table_207_1",
    "Coffee_Table_209_1",
    "Coffee_Table_211_1",
    "Coffee_Table_213_1",
    "Coffee_Table_214_1",
    "Coffee_Table_215_1",
    "Coffee_Table_215_2",
    "Coffee_Table_217_1",
    "Coffee_Table_218_1",
    "Coffee_Table_221_1",
    "Coffee_Table_222_1",
    "Coffee_Table_225_1",
    "Coffee_Table_227_1_1",
    "Coffee_Table_227_2_1",
    "Coffee_Table_228_1",
    "Coffee_Table_229_1",
    "Coffee_Table_230_1",
    "Coffee_Table_315_1",
    "RoboTHOR_coffee_table_bankas",
    "RoboTHOR_coffee_table_fjallbo_v",
    "RoboTHOR_coffee_table_hemnes",
    "RoboTHOR_coffee_table_kragsta",
    "RoboTHOR_coffee_table_lisabo",
    "RoboTHOR_coffee_table_vejmon"
  ],
  "CounterTop": [
    "Countertop_C_10x10",
    "Countertop_C_10x4",
    "Countertop_C_10x6",
    "Countertop_C_10x8",
    "Countertop_C_8x10",
    "Countertop_C_8x4",
    "Countertop_C_8x6",
    "Countertop_C_8x8",
    "Countertop_I_10x2",
    "Countertop_I_2x2",
    "Countertop_I_4x2",
    "Countertop_I_6x2",
    "Countertop_I_8x2",
    "Countertop_Island_10x3",
    "Countertop_Island_4x3",
    "Countertop_Island_6x3",
    "Countertop_Island_8x3",
    "Countertop_L_10x10",
    "Countertop_L_10x4",
    "Countertop_L_10x6",
    "Countertop_L_10x8",
    "Countertop_L_4x10",
    "Countertop_L_4x4",
    "Countertop_L_4x6",
    "Countertop_L_4x8",
    "Countertop_L_6x10",
    "Countertop_L_6x4",
    "Countertop_L_6x6",
    "Countertop_L_6x8",
    "Countertop_L_8x10",
    "Countertop_L_8x4",
    "Countertop_L_8x6",
    "Countertop_L_8x8"
  ],
  "CreditCard": [
    "CreditCard_1",
    "CreditCard_2",
    "CreditCard_3",
    "CreditCard_4"
  ],
  "Cup": [
    "Cup_1",
    "Cup_10",
    "Cup_11",
    "Cup_12",
    "Cup_13",
    "Cup_14",
    "Cup_15",
    "Cup_16",
    "Cup_17",
    "Cup_18",
    "Cup_19",
    "Cup_2",
    "Cup_20",
    "Cup_21",
    "Cup_22",
    "Cup_23",
    "Cup_24",
    "Cup_25",
    "Cup_26",
    "Cup_27",
    "Cup_28",
    "Cup_29",
    "Cup_3",
    "Cup_30",
    "Cup_4",
    "Cup_5",
    "Cup_6",
    "Cup_7",
    "Cup_8",
    "Cup_9",
    "RoboTHOR_cup_ai2_v"
  ],
  "Desk": [
    "Desk_204_1",
    "Desk_229_1",
    "Desk_301_1",
    "Desk_302_1",
    "Desk_303_1",
    "Desk_304_1",
    "Desk_305_1",
    "Desk_306_1",
    "Desk_307_1_1",
    "Desk_307_2_1",
    "Desk_308_1_1",
    "Desk_308_2_1",
    "Desk_310_1",
    "Desk_311_1",
    "Desk_312_1",
    "Desk_313_1",
    "Desk_313_2",
    "Desk_314_1",
    "Desk_315_1",
    "Desk_316_1",
    "Desk_318_1",
    "Desk_320_1_1",
    "Desk_320_2_1",
    "Desk_321_1",
    "Desk_323_1",
    "Desk_326_1",
    "Desk_327_1",
    "Desk_328_1",
    "Desk_329_1",
    "RoboTHOR_desk_alve",
    "RoboTHOR_desk_fjallbo_v",
    "RoboTHOR_desk_gustav",
    "RoboTHOR_desk_lillasen",
    "RoboTHOR_desk_lisabo",
    "RoboTHOR_desk_norrasen"
  ],
  "DeskLamp": [
    "Desk_Lamp_1",
    "Desk_Lamp_10",
    "Desk_Lamp_11",
    "Desk_Lamp_12",
    "Desk_Lamp_13",
    "Desk_Lamp_2",
    "Desk_Lamp_3",
    "Desk_Lamp_4",
    "Desk_Lamp_5",
    "Desk_Lamp_6",
    "Desk_Lamp_7",
    "Desk_Lamp_8",
    "Desk_Lamp_9",
    "RoboTHOR_desk_lamp_ai2_v",
    "RoboTHOR_desk_lamp_arstid_v"
  ],
  "Desktop": [
    "Desktop_316_1"
  ],
  "DiningTable": [
    "Dining_Table_16_1",
    "Dining_Table_16_2",
    "Dining_Table_201_1",
    "Dining_Table_203_1",
    "Dining_Table_204_1",
    "Dining_Table_205_1",
    "Dining_Table_208_1",
    "Dining_Table_208_2",
    "Dining_Table_216_1",
    "Dining_Table_218_1",
    "Dining_Table_21_1",
    "Dining_Table_21_2",
    "Dining_Table_21_3",
    "Dining_Table_221_1",
    "Dining_Table_223_1",
    "Dining_Table_227_1",
    "Dining_Table_228_1",
    "Dining_Table_230_1",
    "Dining_Table_23_1",
    "Dining_Table_23_2",
    "Dining_Table_23_3",
    "Dining_Table_27_1",
    "Dining_Table_7_1",
    "Dining_Table_9_1",
    "RoboTHOR_dining_table_antas",
    "RoboTHOR_dining_table_extendable",
    "RoboTHOR_dining_table_jokkmokk_v",
    "RoboTHOR_dining_table_liatorp",
    "RoboTHOR_dining_table_mella",
    "RoboTHOR_dining_table_norden_gateleg"
  ],
  "DishSponge": [
    "Dish_Sponge_1"
  ],
  "DogBed": [
    "Dog_Bed_1_1",
    "Dog_Bed_1_2",
    "Dog_Bed_2_1"
  ],
  "Doorframe": [
    "Doorframe_1",
    "Doorframe_10",
    "Doorframe_2",
    "Doorframe_3",
    "Doorframe_4",
    "Doorframe_5",
    "Doorframe_6",
    "Doorframe_7",
    "Doorframe_8",
    "Doorframe_9",
    "Doorframe_Double_1",
    "Doorframe_Double_10",
    "Doorframe_Double_2",
    "Doorframe_Double_3",
    "Doorframe_Double_4",
    "Doorframe_Double_5",
    "Doorframe_Double_6",
    "Doorframe_Double_7",
    "Doorframe_Double_8",
    "Doorframe_Double_9"
  ],
  "Doorway": [
    "Doorway_1",
    "Doorway_10",
    "Doorway_2",
    "Doorway_3",
    "Doorway_4",
    "Doorway_5",
    "Doorway_6",
    "Doorway_7",
    "Doorway_8",
    "Doorway_9",
    "Doorway_Double_1",
    "Doorway_Double_10",
    "Doorway_Double_2",
    "Doorway_Double_3",
    "Doorway_Double_4",
    "Doorway_Double_5",
    "Doorway_Double_6",
    "Doorway_Double_7",
    "Doorway_Double_8",
    "Doorway_Double_9"
  ],
  "Dresser": [
    "Dresser_205_1",
    "Dresser_209_1",
    "Dresser_210_1_1",
    "Dresser_210_2_1",
    "Dresser_213_1",
    "Dresser_217_1",
    "Dresser_218_1",
    "Dresser_219_1",
    "Dresser_220_1",
    "Dresser_224_1",
    "Dresser_229_1",
    "Dresser_301_1",
    "Dresser_315_1",
    "Dresser_315_2",
    "Dresser_315_3",
    "Dresser_318_1",
    "Dresser_318_2",
    "Dresser_319_1",
    "Dresser_319_2",
    "Dresser_323_1",
    "Dresser_325_1",
    "Dresser_413_1",
    "RoboTHOR_dresser_aneboda",
    "RoboTHOR_dresser_anes",
    "RoboTHOR_dresser_aspelund",
    "RoboTHOR_dresser_birkeland",
    "RoboTHOR_dresser_hemnes",
    "RoboTHOR_dresser_rast_v"
  ],
  "Dumbbell": [
    "Dumbbell_1_1"
  ],
  "Egg": [
    "Egg_1",
    "Egg_10",
    "Egg_11",
    "Egg_12",
    "Egg_13",
    "Egg_14",
    "Egg_15",
    "Egg_16",
    "Egg_17",
    "Egg_18",
    "Egg_19",
    "Egg_2",
    "Egg_20",
    "Egg_21",
    "Egg_22",
    "Egg_23",
    "Egg_24",
    "Egg_25",
    "Egg_26",
    "Egg_27",
    "Egg_28",
    "Egg_29",
    "Egg_3",
    "Egg_30",
    "Egg_4",
    "Egg_5",
    "Egg_6",
    "Egg_7",
    "Egg_8",
    "Egg_9"
  ],
  "Faucet": [
    "Bathroom_Faucet_1",
    "Bathroom_Faucet_10",
    "Bathroom_Faucet_11",
    "Bathroom_Faucet_12",
    "Bathroom_Faucet_13",
    "Bathroom_Faucet_14",
    "Bathroom_Faucet_15",
    "Bathroom_Faucet_17",
    "Bathroom_Faucet_18",
    "Bathroom_Faucet_19",
    "Bathroom_Faucet_2",
    "Bathroom_Faucet_20",
    "Bathroom_Faucet_21",
    "Bathroom_Faucet_22",
    "Bathroom_Faucet_25",
    "Bathroom_Faucet_26",
    "Bathroom_Faucet_27",
    "Bathroom_Faucet_28",
    "Bathroom_Faucet_3",
    "Bathroom_Faucet_30",
    "Bathroom_Faucet_5",
    "Bathroom_Faucet_7",
    "Bathroom_Faucet_8",
    "Bathroom_Faucet_9",
    "Bathtub_Faucet_1",
    "Bathtub_Faucet_2",
    "Bathtub_Faucet_3",
    "Bathtub_Faucet_4",
    "Bathtub_Faucet_5",
    "Bathtub_Faucet_6",
    "Bathtub_Faucet_7",
    "Bathtub_Faucet_8",
    "Kitchen_Faucet_1",
    "Kitchen_Faucet_2",
    "Kitchen_Faucet_3",
    "Kitchen_Faucet_4",
    "Kitchen_Faucet_5"
  ],
  "FloorLamp": [
    "Floor_Lamp_1",
    "Floor_Lamp_10",
    "Floor_Lamp_11",
    "Floor_Lamp_12",
    "Floor_Lamp_13",
    "Floor_Lamp_14",
    "Floor_Lamp_15",
    "Floor_Lamp_16",
    "Floor_Lamp_17",
    "Floor_Lamp_18",
    "Floor_Lamp_19",
    "Floor_Lamp_2",
    "Floor_Lamp_20",
    "Floor_Lamp_21",
    "Floor_Lamp_22",
    "Floor_Lamp_23",
    "Floor_Lamp_24",
    "Floor_Lamp_25",
    "Floor_Lamp_26",
    "Floor_Lamp_27",
    "Floor_Lamp_28",
    "Floor_Lamp_29",
    "Floor_Lamp_3",
    "Floor_Lamp_30",
    "Floor_Lamp_4",
    "Floor_Lamp_5",
    "Floor_Lamp_6",
    "Floor_Lamp_7",
    "Floor_Lamp_8",
    "Floor_Lamp_9",
    "RoboTHOR_floor_lamp_holmo_v",
    "RoboTHOR_floor_lamp_not_v"
  ],
  "Footstool": [
    "Footstool_1",
    "Footstool_1_1_1",
    "Footstool_1_2_1",
    "Footstool_2",
    "Footstool_2_1",
    "Footstool_3",
    "Footstool_4"
  ],
  "Fork": [
    "Fork_1",
    "RoboTHOR_fork_ai2_v"
  ],
  "Fridge": [
    "Fridge_1",
    "Fridge_10",
    "Fridge_11",
    "Fridge_12",
    "Fridge_13",
    "Fridge_14",
    "Fridge_15",
    "Fridge_16",
    "Fridge_17",
    "Fridge_18",
    "Fridge_19",
    "Fridge_2",
    "Fridge_20",
    "Fridge_21",
    "Fridge_22",
    "Fridge_23",
    "Fridge_24",
    "Fridge_25",
    "Fridge_26",
    "Fridge_27",
    "Fridge_28",
    "Fridge_29",
    "Fridge_3",
    "Fridge_30",
    "Fridge_4",
    "Fridge_5",
    "Fridge_6",
    "Fridge_7",
    "Fridge_8",
    "Fridge_9"
  ],
  "GarbageBag": [
    "GarbageBag_21_1",
    "GarbageBag_21_2"
  ],
  "GarbageCan": [
    "RoboTHOR_garbage_bin_ai2_1_v",
    "bin_1",
    "bin_10",
    "bin_11",
    "bin_12",
    "bin_13",
    "bin_14",
    "bin_15",
    "bin_16",
    "bin_17",
    "bin_18",
    "bin_19",
    "bin_2",
    "bin_20",
    "bin_21",
    "bin_22",
    "bin_23",
    "bin_24",
    "bin_25",
    "bin_26",
    "bin_27",
    "bin_28",
    "bin_29",
    "bin_3",
    "bin_30",
    "bin_4",
    "bin_5",
    "bin_6",
    "bin_7",
    "bin_8",
    "bin_9"
  ],
  "HandTowel": [
    "Hand_Towel_1"
  ],
  "HandTowelHolder": [
    "Hand_Towel_Holder1"
  ],
  "HousePlant": [
    "Houseplant_1",
    "Houseplant_10",
    "Houseplant_11",
    "Houseplant_12",
    "Houseplant_13",
    "Houseplant_14",
    "Houseplant_15",
    "Houseplant_16",
    "Houseplant_17",
    "Houseplant_18",
    "Houseplant_19",
    "Houseplant_2",
    "Houseplant_20",
    "Houseplant_21",
    "Houseplant_22",
    "Houseplant_23",
    "Houseplant_24",
    "Houseplant_25",
    "Houseplant_26",
    "Houseplant_27",
    "Houseplant_28",
    "Houseplant_29",
    "Houseplant_3",
    "Houseplant_30",
    "Houseplant_4",
    "Houseplant_5",
    "Houseplant_6",
    "Houseplant_7",
    "Houseplant_8",
    "Houseplant_9",
    "RoboTHOR_houseplant_ai2_2_v"
  ],
  "Kettle": [
    "Kettle_1"
  ],
  "KeyChain": [
    "Keychain_1",
    "Keychain_2",
    "Keychain_3"
  ],
  "Knife": [
    "Knife_1",
    "Knife_2",
    "Knife_3",
    "Knife_4",
    "Knife_5",
    "Knife_6",
    "Knife_7"
  ],
  "Ladle": [
    "Ladle_1",
    "Ladle_2",
    "Ladle_3"
  ],
  "Laptop": [
    "Laptop_1",
    "Laptop_10",
    "Laptop_11",
    "Laptop_12",
    "Laptop_13",
    "Laptop_14",
    "Laptop_15",
    "Laptop_16",
    "Laptop_17",
    "Laptop_18",
    "Laptop_19",
    "Laptop_2",
    "Laptop_20",
    "Laptop_21",
    "Laptop_22",
    "Laptop_23",
    "Laptop_24",
    "Laptop_25",
    "Laptop_26",
    "Laptop_27",
    "Laptop_28",
    "Laptop_29",
    "Laptop_3",
    "Laptop_30",
    "Laptop_4",
    "Laptop_5",
    "Laptop_6",
    "Laptop_7",
    "Laptop_8",
    "Laptop_9",
    "RoboTHOR_laptop_props_america_1_v"
  ],
  "LaundryHamper": [
    "Laundry_Hamper_1_1",
    "Laundry_Hamper_1_2",
    "Laundry_Hamper_1_3",
    "Laundry_Hamper_1_4"
  ],
  "Lettuce": [
    "Lettuce_1",
    "Lettuce_10",
    "Lettuce_11",
    "Lettuce_12",
    "Lettuce_13",
    "Lettuce_14",
    "Lettuce_15",
    "Lettuce_16",
    "Lettuce_17",
    "Lettuce_18",
    "Lettuce_19",
    "Lettuce_2",
    "Lettuce_20",
    "Lettuce_21",
    "Lettuce_22",
    "Lettuce_23",
    "Lettuce_24",
    "Lettuce_25",
    "Lettuce_26",
    "Lettuce_27",
    "Lettuce_28",
    "Lettuce_29",
    "Lettuce_3",
    "Lettuce_30",
    "Lettuce_4",
    "Lettuce_5",
    "Lettuce_6",
    "Lettuce_7",
    "Lettuce_8",
    "Lettuce_9"
  ],
  "LightSwitch": [
    "Light_Switch_1",
    "Light_Switch_10",
    "Light_Switch_11",
    "Light_Switch_12",
    "Light_Switch_13",
    "Light_Switch_14",
    "Light_Switch_15",
    "Light_Switch_16",
    "Light_Switch_17",
    "Light_Switch_18",
    "Light_Switch_19",
    "Light_Switch_2",
    "Light_Switch_20",
    "Light_Switch_21",
    "Light_Switch_22",
    "Light_Switch_23",
    "Light_Switch_24",
    "Light_Switch_25",
    "Light_Switch_26",
    "Light_Switch_27",
    "Light_Switch_28",
    "Light_Switch_29",
    "Light_Switch_3",
    "Light_Switch_30",
    "Light_Switch_4",
    "Light_Switch_5",
    "Light_Switch_6",
    "Light_Switch_7",
    "Light_Switch_8",
    "Light_Switch_9"
  ],
  "Microwave": [
    "Microwave_1",
    "Microwave_10",
    "Microwave_11",
    "Microwave_12",
    "Microwave_13",
    "Microwave_14",
    "Microwave_15",
    "Microwave_16",
    "Microwave_17",
    "Microwave_18",
    "Microwave_19",
    "Microwave_2",
    "Microwave_20",
    "Microwave_21",
    "Microwave_22",
    "Microwave_23",
    "Microwave_24",
    "Microwave_25",
    "Microwave_26",
    "Microwave_27",
    "Microwave_28",
    "Microwave_29",
    "Microwave_3",
    "Microwave_30",
    "Microwave_4",
    "Microwave_5",
    "Microwave_6",
    "Microwave_7",
    "Microwave_8",
    "Microwave_9"
  ],
  "Mug": [
    "Mug_1",
    "Mug_2",
    "Mug_3",
    "RoboTHOR_mug_ai2_1_v",
    "RoboTHOR_mug_ai2_2_v"
  ],
  "Newspaper": [
    "Newspaper_1",
    "Newspaper_2",
    "Newspaper_3",
    "Newspaper_4",
    "Newspaper_5"
  ],
  "Ottoman": [
    "Ottoman_203_1",
    "Ottoman_205_1",
    "Ottoman_208_1",
    "Ottoman_210_1"
  ],
  "Painting": [
    "Wall_Decor_Painting_1",
    "Wall_Decor_Painting_10",
    "Wall_Decor_Painting_1V",
    "Wall_Decor_Painting_2",
    "Wall_Decor_Painting_2V",
    "Wall_Decor_Painting_3",
    "Wall_Decor_Painting_3V",
    "Wall_Decor_Painting_4",
    "Wall_Decor_Painting_5",
    "Wall_Decor_Painting_6",
    "Wall_Decor_Painting_7",
    "Wall_Decor_Painting_8",
    "Wall_Decor_Painting_9",
    "Wall_Decor_Photo_1",
    "Wall_Decor_Photo_10",
    "Wall_Decor_Photo_1V",
    "Wall_Decor_Photo_2",
    "Wall_Decor_Photo_2V",
    "Wall_Decor_Photo_3",
    "Wall_Decor_Photo_3V",
    "Wall_Decor_Photo_4",
    "Wall_Decor_Photo_5",
    "Wall_Decor_Photo_6",
    "Wall_Decor_Photo_7",
    "Wall_Decor_Photo_8",
    "Wall_Decor_Photo_9"
  ],
  "Pan": [
    "Pan_1",
    "Pan_10",
    "Pan_11",
    "Pan_12",
    "Pan_13",
    "Pan_14",
    "Pan_15",
    "Pan_16",
    "Pan_17",
    "Pan_18",
    "Pan_19",
    "Pan_2",
    "Pan_20",
    "Pan_21",
    "Pan_22",
    "Pan_23",
    "Pan_24",
    "Pan_25",
    "Pan_26",
    "Pan_27",
    "Pan_28",
    "Pan_29",
    "Pan_3",
    "Pan_30",
    "Pan_4",
    "Pan_5",
    "Pan_6",
    "Pan_7",
    "Pan_8",
    "Pan_9"
  ],
  "PaperTowelRoll": [
    "Paper_Towel_1"
  ],
  "Pen": [
    "Pen_1",
    "Pen_2",
    "Pen_3",
    "Pen_4",
    "RoboTHOR_pen_signo_v"
  ],
  "Pencil": [
    "Pencil_1",
    "Pencil_2",
    "Pencil_3",
    "Pencil_4",
    "Pencil_5",
    "Pencil_6",
    "Pencil_7",
    "RoboTHOR_pencil_amazon_basics_v"
  ],
  "PepperShaker": [
    "Pepper_Shaker_1",
    "Pepper_Shaker_2",
    "RoboTHOR_salt_pepper_shaker_bnyd_pepper_v"
  ],
  "Pillow": [
    "RoboTHOR_pillow_dvala_v",
    "RoboTHOR_pillow_sanglarka_1_v",
    "pillow_1",
    "pillow_10",
    "pillow_11",
    "pillow_12",
    "pillow_13",
    "pillow_14",
    "pillow_15",
    "pillow_16",
    "pillow_17",
    "pillow_18",
    "pillow_19",
    "pillow_2",
    "pillow_20",
    "pillow_21",
    "pillow_22",
    "pillow_23",
    "pillow_24",
    "pillow_25",
    "pillow_26",
    "pillow_27",
    "pillow_28",
    "pillow_29",
    "pillow_3",
    "pillow_30",
    "pillow_4",
    "pillow_5",
    "pillow_6",
    "pillow_7",
    "pillow_8",
    "pillow_9"
  ],
  "Plate": [
    "Plate_1",
    "Plate_10",
    "Plate_11",
    "Plate_12",
    "Plate_13",
    "Plate_14",
    "Plate_15",
    "Plate_16",
    "Plate_17",
    "Plate_18",
    "Plate_19",
    "Plate_2",
    "Plate_20",
    "Plate_21",
    "Plate_22",
    "Plate_23",
    "Plate_24",
    "Plate_25",
    "Plate_26",
    "Plate_27",
    "Plate_28",
    "Plate_29",
    "Plate_3",
    "Plate_30",
    "Plate_4",
    "Plate_5",
    "Plate_6",
    "Plate_7",
    "Plate_8",
    "Plate_9",
    "RoboTHOR_plate_ai2_v"
  ],
  "Plunger": [
    "Plunger_1",
    "Plunger_2",
    "Plunger_3"
  ],
  "Pot": [
    "Pot_1",
    "Pot_10",
    "Pot_11",
    "Pot_12",
    "Pot_13",
    "Pot_14",
    "Pot_15",
    "Pot_16",
    "Pot_17",
    "Pot_18",
    "Pot_19",
    "Pot_2",
    "Pot_20",
    "Pot_21",
    "Pot_22",
    "Pot_23",
    "Pot_24",
    "Pot_25",
    "Pot_26",
    "Pot_27",
    "Pot_28",
    "Pot_29",
    "Pot_3",
    "Pot_30",
    "Pot_4",
    "Pot_5",
    "Pot_6",
    "Pot_7",
    "Pot_8",
    "Pot_9"
  ],
  "Potato": [
    "Potato_1",
    "Potato_10",
    "Potato_11",
    "Potato_12",
    "Potato_13",
    "Potato_14",
    "Potato_15",
    "Potato_16",
    "Potato_17",
    "Potato_18",
    "Potato_19",
    "Potato_2",
    "Potato_20",
    "Potato_21",
    "Potato_22",
    "Potato_23",
    "Potato_24",
    "Potato_25",
    "Potato_26",
    "Potato_27",
    "Potato_28",
    "Potato_29",
    "Potato_3",
    "Potato_30",
    "Potato_4",
    "Potato_5",
    "Potato_6",
    "Potato_7",
    "Potato_8",
    "Potato_9"
  ],
  "RemoteControl": [
    "Remote_1",
    "Remote_2",
    "Remote_3",
    "RoboTHOR_remote_coolux_v"
  ],
  "RoomDecor": [
    "Room_Decor_1_1",
    "Room_Decor_1_2"
  ],
  "Safe": [
    "Safe_18_1",
    "Safe_18_2"
  ],
  "SaltShaker": [
    "RoboTHOR_salt_pepper_shaker_bnyd_salt_v",
    "Salt_Shaker_1",
    "Salt_Shaker_2"
  ],
  "ScrubBrush": [
    "Scrub_Brush_1"
  ],
  "ShelvingUnit": [
    "RoboTHOR_shelving_unit_kallax_large",
    "RoboTHOR_shelving_unit_kallax_small_2_v",
    "Shelving_Unit_001_1",
    "Shelving_Unit_206_1",
    "Shelving_Unit_206_2",
    "Shelving_Unit_215_1",
    "Shelving_Unit_219_1",
    "Shelving_Unit_303_1",
    "Shelving_Unit_307_1",
    "Shelving_Unit_313_1",
    "Shelving_Unit_319_1",
    "Shelving_Unit_324_1",
    "Shelving_Unit_325_1",
    "Shelving_Unit_325_2"
  ],
  "ShowerCurtain": [
    "Shower_Curtain_1",
    "Shower_Curtain_2"
  ],
  "ShowerHead": [
    "Shower_Head_1",
    "Shower_Head_2"
  ],
  "SideTable": [
    "RoboTHOR_side_table_fornbro",
    "RoboTHOR_side_table_havsta_v",
    "RoboTHOR_side_table_hol",
    "RoboTHOR_side_table_hopen",
    "RoboTHOR_side_table_nested_havsta_v",
    "RoboTHOR_side_table_strind",
    "RoboTHOR_side_table_tingby",
    "Side_Table_201_1_1",
    "Side_Table_201_2_1",
    "Side_Table_201_3_1",
    "Side_Table_202_1",
    "Side_Table_203_1",
    "Side_Table_203_2",
    "Side_Table_203_3",
    "Side_Table_205_1_1",
    "Side_Table_205_2_1",
    "Side_Table_205_2_2",
    "Side_Table_207_1",
    "Side_Table_209_1_1",
    "Side_Table_209_2_1",
    "Side_Table_210_1_1",
    "Side_Table_210_2_1",
    "Side_Table_213_1_1",
    "Side_Table_213_2_1",
    "Side_Table_213_3_1",
    "Side_Table_213_4_1",
    "Side_Table_214_1",
    "Side_Table_215_1",
    "Side_Table_216_1_1",
    "Side_Table_216_2_1",
    "Side_Table_216_3_1",
    "Side_Table_217_1",
    "Side_Table_218_1",
    "Side_Table_219_1",
    "Side_Table_21_1",
    "Side_Table_220_1",
    "Side_Table_220_2",
    "Side_Table_222_1_1",
    "Side_Table_222_2_1",
    "Side_Table_223_1",
    "Side_Table_223_2",
    "Side_Table_224_1",
    "Side_Table_225_1",
    "Side_Table_228_1_1",
    "Side_Table_228_2_1",
    "Side_Table_229_1_1",
    "Side_Table_229_2_1",
    "Side_Table_230_1",
    "Side_Table_302_1_1",
    "Side_Table_302_1_2",
    "Side_Table_302_1_3",
    "Side_Table_302_1_4",
    "Side_Table_302_1_5",
    "Side_Table_302_1_6",
    "Side_Table_302_1_7",
    "Side_Table_302_2_1",
    "Side_Table_303_1_1",
    "Side_Table_303_2_1",
    "Side_Table_305_1",
    "Side_Table_306_1",
    "Side_Table_306_2",
    "Side_Table_307_1",
    "Side_Table_309_1",
    "Side_Table_310_1",
    "Side_Table_311_1_1",
    "Side_Table_311_2_1",
    "Side_Table_311_2_2",
    "Side_Table_313_1",
    "Side_Table_317_1",
    "Side_Table_320_1",
    "Side_Table_322_1",
    "Side_Table_329_1",
    "Side_Table_3_1",
    "Side_Table_401_1"
  ],
  "Sink": [
    "Sink_1",
    "Sink_10",
    "Sink_11",
    "Sink_12",
    "Sink_13",
    "Sink_14",
    "Sink_15",
    "Sink_16",
    "Sink_17",
    "Sink_18",
    "Sink_19",
    "Sink_2",
    "Sink_20",
    "Sink_21",
    "Sink_22",
    "Sink_23",
    "Sink_24",
    "Sink_25",
    "Sink_26",
    "Sink_27",
    "Sink_28",
    "Sink_29",
    "Sink_3",
    "Sink_30",
    "Sink_4",
    "Sink_5",
    "Sink_6",
    "Sink_7",
    "Sink_8",
    "Sink_9"
  ],
  "SoapBar": [
    "Soap_Bar_1"
  ],
  "SoapBottle": [
    "Soap_Bottle_1",
    "Soap_Bottle_10",
    "Soap_Bottle_11",
    "Soap_Bottle_12",
    "Soap_Bottle_13",
    "Soap_Bottle_14",
    "Soap_Bottle_15",
    "Soap_Bottle_16",
    "Soap_Bottle_17",
    "Soap_Bottle_18",
    "Soap_Bottle_19",
    "Soap_Bottle_2",
    "Soap_Bottle_20",
    "Soap_Bottle_21",
    "Soap_Bottle_22",
    "Soap_Bottle_23",
    "Soap_Bottle_24",
    "Soap_Bottle_25",
    "Soap_Bottle_26",
    "Soap_Bottle_27",
    "Soap_Bottle_28",
    "Soap_Bottle_29",
    "Soap_Bottle_3",
    "Soap_Bottle_30",
    "Soap_Bottle_4",
    "Soap_Bottle_5",
    "Soap_Bottle_6",
    "Soap_Bottle_7",
    "Soap_Bottle_8",
    "Soap_Bottle_9"
  ],
  "Sofa": [
    "RoboTHOR_sofa_alrid",
    "RoboTHOR_sofa_ektorp_v",
    "RoboTHOR_sofa_kramfors",
    "RoboTHOR_sofa_solsta",
    "RoboTHOR_sofa_vreta",
    "Sofa_201_1",
    "Sofa_201_2",
    "Sofa_201_3",
    "Sofa_201_4",
    "Sofa_203_1",
    "Sofa_204_1",
    "Sofa_205_1",
    "Sofa_205_2",
    "Sofa_206_1",
    "Sofa_207_1",
    "Sofa_207_2",
    "Sofa_207_3",
    "Sofa_207_4",
    "Sofa_207_5",
    "Sofa_208_1",
    "Sofa_210_1",
    "Sofa_213_1",
    "Sofa_214_1",
    "Sofa_214_2",
    "Sofa_215_1",
    "Sofa_216_1",
    "Sofa_216_2",
    "Sofa_216_3",
    "Sofa_216_4",
    "Sofa_218_1",
    "Sofa_218_2",
    "Sofa_220_1",
    "Sofa_221_1",
    "Sofa_223_1",
    "Sofa_223_2",
    "Sofa_223_3",
    "Sofa_227_1"
  ],
  "Spatula": [
    "Spatula_1"
  ],
  "Spoon": [
    "Spoon_1"
  ],
  "SprayBottle": [
    "RoboTHOR_spray_bottle_kramig_v",
    "Spray_Bottle_1",
    "Spray_Bottle_2",
    "Spray_Bottle_3",
    "Spray_Bottle_4",
    "Spray_Bottle_5",
    "Spray_Bottle_6",
    "Spray_Bottle_7",
    "Spray_Bottle_8"
  ],
  "Statue": [
    "Dog_Statue_1",
    "Dog_Statue_2",
    "Dog_Statue_3",
    "Dog_Statue_4",
    "Fertility_Statue_1",
    "Fertility_Statue_2",
    "Fertility_Statue_3",
    "Hand_Statue_1",
    "Hand_Statue_2",
    "Hand_Statue_3",
    "Stone_Statue_1",
    "Stone_Statue_2",
    "Stone_Statue_3",
    "Stone_Statue_4",
    "Towel_Statue_1",
    "Towel_Statue_2",
    "Towel_Statue_3",
    "Waving_Statue_1",
    "Waving_Statue_2",
    "Waving_Statue_3"
  ],
  "Stool": [
    "Stool_1_1",
    "Stool_1_2",
    "Stool_1_3",
    "Stool_2_1",
    "Stool_2_2",
    "Stool_2_3",
    "Stool_2_4",
    "Stool_3_1",
    "Stool_4_1",
    "Stool_5_1"
  ],
  "TVStand": [
    "TV_Stand_201_1",
    "TV_Stand_202_1",
    "TV_Stand_204_1",
    "TV_Stand_206_1",
    "TV_Stand_206_2",
    "TV_Stand_206_3",
    "TV_Stand_211_1",
    "TV_Stand_212_1",
    "TV_Stand_220_1",
    "TV_Stand_222_1",
    "TV_Stand_223_1"
  ],
  "TableTopDecor": [
    "Tabletop_Decor_1_1"
  ],
  "TeddyBear": [
    "Teddy_Bear_1",
    "Teddy_Bear_2"
  ],
  "Television": [
    "RoboTHOR_television_props_america_1_v",
    "Television_1",
    "Television_10",
    "Television_11",
    "Television_12",
    "Television_13",
    "Television_14",
    "Television_15",
    "Television_16",
    "Television_17",
    "Television_18",
    "Television_19",
    "Television_2",
    "Television_20",
    "Television_21",
    "Television_22",
    "Television_23",
    "Television_24",
    "Television_25",
    "Television_26",
    "Television_27",
    "Television_28",
    "Television_29",
    "Television_2_1",
    "Television_3",
    "Television_30",
    "Television_4",
    "Television_5",
    "Television_6",
    "Television_7",
    "Television_8",
    "Television_9"
  ],
  "TennisRacket": [
    "RoboTHOR_tennis_racquet_speed_kids_v",
    "Tennis_Racquet_1",
    "Tennis_Racquet_2",
    "Tennis_Racquet_3",
    "Tennis_Racquet_4",
    "Tennis_Racquet_5"
  ],
  "TissueBox": [
    "Tissue_Box_1"
  ],
  "Toaster": [
    "Toaster_1",
    "Toaster_10",
    "Toaster_11",
    "Toaster_12",
    "Toaster_13",
    "Toaster_14",
    "Toaster_15",
    "Toaster_16",
    "Toaster_17",
    "Toaster_18",
    "Toaster_19",
    "Toaster_2",
    "Toaster_20",
    "Toaster_21",
    "Toaster_22",
    "Toaster_23",
    "Toaster_24",
    "Toaster_25",
    "Toaster_26",
    "Toaster_27",
    "Toaster_28",
    "Toaster_29",
    "Toaster_3",
    "Toaster_30",
    "Toaster_4",
    "Toaster_5",
    "Toaster_6",
    "Toaster_7",
    "Toaster_8",
    "Toaster_9"
  ],
  "Toilet": [
    "Toilet_1",
    "Toilet_2"
  ],
  "ToiletPaper": [
    "Toilet_Paper",
    "Toilet_Paper_Used_Up"
  ],
  "ToiletPaperHanger": [
    "Toilet_Paper_Hanger_1",
    "Toilet_Paper_Hanger_10",
    "Toilet_Paper_Hanger_11",
    "Toilet_Paper_Hanger_12",
    "Toilet_Paper_Hanger_13",
    "Toilet_Paper_Hanger_14",
    "Toilet_Paper_Hanger_15",
    "Toilet_Paper_Hanger_16",
    "Toilet_Paper_Hanger_17",
    "Toilet_Paper_Hanger_18",
    "Toilet_Paper_Hanger_19",
    "Toilet_Paper_Hanger_2",
    "Toilet_Paper_Hanger_20",
    "Toilet_Paper_Hanger_21",
    "Toilet_Paper_Hanger_22",
    "Toilet_Paper_Hanger_23",
    "Toilet_Paper_Hanger_24",
    "Toilet_Paper_Hanger_25",
    "Toilet_Paper_Hanger_26",
    "Toilet_Paper_Hanger_27",
    "Toilet_Paper_Hanger_28",
    "Toilet_Paper_Hanger_29",
    "Toilet_Paper_Hanger_3",
    "Toilet_Paper_Hanger_30",
    "Toilet_Paper_Hanger_4",
    "Toilet_Paper_Hanger_5",
    "Toilet_Paper_Hanger_6",
    "Toilet_Paper_Hanger_7",
    "Toilet_Paper_Hanger_8",
    "Toilet_Paper_Hanger_9"
  ],
  "Tomato": [
    "Tomato_1",
    "Tomato_10",
    "Tomato_11",
    "Tomato_12",
    "Tomato_13",
    "Tomato_14",
    "Tomato_15",
    "Tomato_16",
    "Tomato_17",
    "Tomato_18",
    "Tomato_19",
    "Tomato_2",
    "Tomato_20",
    "Tomato_21",
    "Tomato_22",
    "Tomato_23",
    "Tomato_24",
    "Tomato_25",
    "Tomato_26",
    "Tomato_27",
    "Tomato_28",
    "Tomato_29",
    "Tomato_3",
    "Tomato_30",
    "Tomato_4",
    "Tomato_5",
    "Tomato_6",
    "Tomato_7",
    "Tomato_8",
    "Tomato_9"
  ],
  "Towel": [
    "Bath_Towel_1",
    "Bath_Towel_2",
    "Bath_Towel_3"
  ],
  "TowelHolder": [
    "Bath_Towel_Holder1"
  ],
  "VacuumCleaner": [
    "Vacuum_Cleaner_1_1"
  ],
  "Vase": [
    "RoboTHOR_vase_stilren_v",
    "Vase_Decorative_1",
    "Vase_Flat_1",
    "Vase_Flat_2",
    "Vase_Flat_3",
    "Vase_Flat_4",
    "Vase_Flat_5",
    "Vase_Medium_1",
    "Vase_Medium_2",
    "Vase_Medium_3",
    "Vase_Medium_4",
    "Vase_Medium_5",
    "Vase_Open_1",
    "Vase_Open_2",
    "Vase_Open_3",
    "Vase_Tall_1",
    "Vase_Tall_2",
    "Vase_Tall_3",
    "Vase_Tall_4",
    "Vase_Tall_5"
  ],
  "WashingMachine": [
    "Washing_Machine_1",
    "Washing_Machine_2"
  ],
  "Watch": [
    "Watch_1",
    "Watch_2"
  ],
  "WateringCan": [
    "Watering_Can_1"
  ],
  "Window": [
    "Window_Bay_1",
    "Window_Bay_2",
    "Window_Bay_3",
    "Window_Fixed_36x48",
    "Window_Fixed_60x36",
    "Window_Fixed_60x48",
    "Window_Fixed_60x72",
    "Window_Fixed_96x48",
    "Window_Fixed_96x72",
    "Window_Hung_32x60",
    "Window_Hung_36x32",
    "Window_Hung_44x60",
    "Window_Hung_48x24",
    "Window_Hung_48x32",
    "Window_Hung_48x44",
    "Window_Slider_36x36",
    "Window_Slider_48x24",
    "Window_Slider_48x36",
    "Window_Slider_48x48",
    "Window_Slider_60x36",
    "Window_Slider_60x48"
  ],
  "WineBottle": [
    "Wine_Bottle_1"
  ]
}


PICKUPABLE_OBJECTS_PROC = list(
    sorted(
        [
            object_type
            for object_type, properties in OBJECT_TYPES_WITH_PROPERTIES.items()
            if properties["pickupable"]
        ]
    )
)

OPENABLE_OBJECTS_PROC = list(
    sorted(
        [
            object_type
            for object_type, properties in OBJECT_TYPES_WITH_PROPERTIES.items()
            if properties["openable"] and not properties["pickupable"]
        ]
    )
)

RECEPTACLES_ONLY_PORC = list(
    sorted(
        [
            object_type
            for object_type, properties in OBJECT_TYPES_WITH_PROPERTIES.items()
            if properties["receptacle"] and not properties["pickupable"]
        ]
    )
)
